RELEVANT_POSITIONS_KEYWORDS = {
    "backend", "development", "server-side", "server side", "object oriented programming", "solid",
    "test-driven development", "test driven development", "tdd", "microservices", "architecture", "scalability",
    "cloud", "c#", ".net", "ruby", "kotlin", "node.js", "golang", "java", "python", "web development",
    "api", "database", "sql", "nosql", "mongodb", "redis", "elasticsearch", "kafka", "aws", "amazon web services",
    "docker", "container", "kubernetes", "ci/cd", "ci cd", "agile", "restful", "rest", "distributed system",
    "data structures", "algorithms", "linux", "networking", "protocols", "virtualization", "technologies", "technology",
    "open-source", "open source", "containerization", "stream processing", "big data", "reactive", "programming",
    "high-throughput systems", "system design", "high availability",
    'Systems', 'Metrics', 'Solutions', 'Software', 'product', 'Fullstack', 'Cyber', 'Research', 'Web', 'Wire', 'System',
    'Senior', 'Engineering', 'Engineer', 'Functional', 'Embedded', 'Autonomous', 'AI', 'Developer',
    'solution architecture', 'version control', 'vue', 'chatbots', 'cloud engineer',
    'data lineage', 'model deployment', 'elastic search', 'tls', 'mysql', 'hybrid', 'elk stack', 'react native',
    'webpack', 'stress testing', 'spring boot', 'high availability', 'developer evangelism', 'data lakes',
    'ux designer', 'html', 'it operations', 'data privacy', 'php', 'api', 'web scraping', 'aws', 'rails',
    'software architecture', 'backend', 'perl', 'gcp', 'ios', 'time-series databases',
    'developer advocacy', 'php', 'sales engineering', 'system testing',
    'framework', 'ai fairness', 'paas', 'reverse engineering',
    'computer vision', 'ai frameworks', 'vulnerability assessment', 'sqlite', 'frontend', 'database', 'qa',
    'unit testing', 'serverless', 'sql', 'javascript', 'natural language processing', 'data pipelines',
    'backup', 'azure', 'azure', 'lambda', 'r&d', 'mobile', 'docker', 'responsible ai', 'restful api',
    'cyber defense', 'react', 'feature engineering', 'github',
    'data reconciliation', 'ai research', 'multi-factor authentication', 'sdlc', 'sre', 'kafka', 'pipeline',
    'acceptance testing', 'machine learning', 'ai innovation', 'healthtech', 'google cloud platform', 'xamarin',
    'data warehousing', 'react', 'ai applications', 'threat hunting', 'senior', 'chief technology officer',
    'internship', 'open source', 'kotlin', 'a/b testing', 'user research', 'network engineer', 'mariadb',
    'asset management', 'model training', 'typescript', 'algorithm', 'forensics', 'mlops',
    # 'ai transparency', 'data engineering', 'part-time', 'data structures', 'flutter', 'sql', 'etl',
    # 'technical lead', 'data engineer', 'product management', 'coding bootcamp', 'soc 2', 'networking',
    # 'hardware', 'edtech', 'growth', 'alerting', 'performance optimization', 'raspberry pi', 'rust',
    # 'deep learning', 'software engineering', 'equity', 'ci/cd', 'git', 'gitlab', 'django', 'explainable ai',
    # 'grafana', 'automation', 'software engineer', 'security operations', 'functions', 'mysql',
    # 'model governance', 'consultant', 'load testing', 'mfa', 'big tech', 'diversity', 'vpn', 'mongodb',
    # 'account management', 'ai use cases', 'innovation', 'kubernetes', 'ruby', 'angular', 'mid level', 'seo',
    # 'developer', 'bioinformatics', 'gcp', 'customer success', 'application', 'ssl', 'high-performance',
    # 'functional programming', 'incident response', 'sql server', 'kanban', 'platform engineering',
    # 'test-driven development', 'pto', 'big data', 'soap', 'cloud computing', 'medtech', 'data integration',
    # 'leadership', 'research and development', 'go', 'service desk', 'culture fit', 'firewalls',
    # 'patch management', 'privilege access management', 'ccpa', 'cloud', 'ruby', 'sem', 'ai interpretability',
    # 'usability', 'iot', 'compliance', 'malware analysis', 'rest', 'embedded systems', 'risk assessment',
    # 'developer relations', 'network security', 'community management', 'postgresql', 'kubernetes',
    # 'text mining', 'virtualization', 'compiler', 'observability', 'ai apis', 'paid time off', 'jira', 'r',
    # 'scalability', 'mongodb', 'growth hacking', 'cybersecurity', 'ai development', 'principal', 'permanent',
    # 'benefits', 'site reliability engineering', 'incident management', 'java', 'iaas', 'css', 'hadoop',
    # 'computer science', 'quantum computing', 'full-stack', 'elixir', 'data enrichment', 'ai platforms',
    # 'ai privacy', 'continuous integration', 'devops', 'swift', 'influxdb', 'iam', 'data validation',
    # 'data modeling', 'ai performance', 'hypervisor', 'system administration', 'data federation',
    # 'data transformation', 'virtual reality', 'collaboration', 'qa engineer', 'node.js', 'content marketing',
    # 'threat modeling', 'parallel computing', 'engineer', 'swift', 'onsite', 'software architect', 'nist',
    # 'data mining', 'restore', 'regression testing', 'biotech', 'kibana', 'game development', 'couchdb', 'scrum',
    # 'mobile development', 'linux', 'user testing', 'dba', 'mentorship', 'data aggregation', 'augmented reality',
    # 'full stack', 'containerization', 'ethical ai', 'devsecops', 'pair programming', 'ai', 'ai solutions',
    # 'ips', 'agile', 'ai optimization', 'post-sales', 'enterprise software', 'architecture', 'accessibility',
    # 'javascript', 'edge computing', 'ai risk management', 'dgraph', 'staff', 'neo4j', 'helpdesk',
    # 'ai governance', 'ai transformation', 'performance testing', 'statistical analysis',
    # 'scrum master', 'semi-supervised learning', 'ai best practices', 'tensorflow',
    # 'object-oriented programming', 'ai security', 'ar', 'lead', 'recurrent neural networks', 'cross-functional',
    # 'endpoint protection', 'style guides', 'blockchain', 'ai operations', 'marketing', 'objective-c',
    # 'data science', 'owasp', 'software as a service', 'data normalization', 'ai strategy', 'golang', 'aiops',
    # 'encryption', 'agile coach', 'python', 'user experience', 'bitbucket', 'zero trust', 'data catalog',
    # 'metadata management', 'rpc', 'ecommerce', 'distributed systems', 'app', 'ai management', 'monitoring',
    # 'startup', 'code review', 'cryptography', 'oracle', 'dashboard', 'library', 'ai ethics', 'kanban',
    # 'ai libraries', 'java', 'programmer', 'contract', 'business intelligence', 'nlp', 'ai tools',
    # 'configuration management', 'rust', 'recommendation systems', 'remote work', 'frontend technologies',
    # 'corporate', 'digital marketing', 'clean code', 'vp of engineering', 'graph databases', 'wireframing',
    # 'desktop applications', 'vue.js', 'team player', 'system administrator', 'faas', 'grpc', 'data cleansing',
    # 'google cloud', 'pci-dss', 'data visualization', 'convolutional neural networks', 'ui/ux', 'freelance',
    # 'data stewardship', 'competitive compensation', 'platform as a service', 'work-life balance', 'flask',
    # 'neural networks', 'waterfall', 'logging', 'node.js', '5g', 'business continuity', 'code', 'aws',
    # 'prometheus', 'descriptive analytics', 'event-driven', 'dashboards', 'ai bias', 'virtual assistants',
    # 'angular', 'git', 'gdpr', 'professional development', 'scale-up', 'full-time', 'fintech',
    # 'infrastructure as a service', 'prescriptive analytics', 'sdk', 'wireless technology', 'mdm', 'intern',
    # 'api', '401(k)', 'nosql', 'docker', 'b2b', 'product manager', 'logstash', 'microservices',
    # 'web development', 'ai trends', 'devops', 'timescaledb', 'change management', 'predictive analytics',
    # 'stock options', 'pre-sales', 'pam', 'penetration testing', 'reporting', 'ai lifecycle management',
    # 'webassembly', 'ai sdks', 'ids', 'data analyst', 'graphql', 'b2c', 'ethical hacker', 'disaster recovery',
    # 'identity and access management', 'supervised learning', 'restful', 'tester', 'ai compliance', 'cto',
    # 'saas', 'data governance', 'ai scalability', 'internet of things', 'software development', 'monolithic',
    # 'mobile applications', 'ai accountability', 'social media', 'continuous deployment', 'penetration tester',
    # 'sso', 'vulnerability management', 'web applications', 'image processing', 'amazon web services',
    # 'automation engineer', 'machine learning models', 'personalization', 'data migration', 'model evaluation',
    # 'rails', 'release management', 'python', 'vmware', 'artificial intelligence', 'entrepreneurial',
    # 'entry level', 'technical support', 'digital transformation', 'graphql', 'hipaa', 'data scientist',
    # 'enterprise', 'data architecture', 'android', 'itil', 'model monitoring', 'product marketing',
    # 'data security', 'scala', 'scala', 'problem management', 'html/css', 'metrics', 'security testing',
    # 'data analysis', 'ui designer', 'c++', 'nosql', 'business analyst', 'key management',
    # 'master data management', 'backend technologies', 'postgresql', 'inclusive', 'spark', 'analytics',
    # 'competitive salary', 'best practices', 'design systems', 'software development lifecycle',
    # 'project manager', 'engineering manager', 'junior', 'cassandra', 'saas', 'robotic process automation',
    # 'reinforcement learning', 'database administrator', 'siem', 'object-oriented', 'customer support',
    # 'security clearance', 'machine vision', 'remote', 'speech recognition', 'integration testing',
    # 'ai deployment', 'soc', 'tech lead', 'health insurance', 'github', 'prototyping', 'startup culture'
}
