import collections

FORBIDDEN_RESPONSE_PAGES = {
    "0086 Ltd": "https://grabjobs.co/uk/companies/0086-ltd-2197904/careers",
    "1 Bishops Avenue Limited": "https://oneavenuegroup.com/careers-with-us/",
    "107 Cannon Street Limited": "https://www.corfinancialgroup.com/contact-us/",
    "12B Solicitors Limited": "https://solicitors.lawsociety.org.uk/office/621097/12b-solicitors-limited",
    "14 PROMOTIONS (TRADE) LIMITED": "https://uk.indeed.com/q-14-promotions-trade-jobs.html",
    "14 Septembre London Limited": "https://www.dezeenjobs.com/company/14-septembre-london/",
    "1783 Limited": "https://1783group.com/careers/",
    "186 London Limited": "https://uk.indeed.com/q-186-l-london-jobs.html",
    "18A Charing Cross Dental Surgery": "https://uk.indeed.com/cmp/18a-Charing-Cross-Dental-Surgery-2",
    "18APR Limited": "https://uk.indeed.com/q-apr-company-jobs.html",
    "1E Limited": "https://www.1e.com/careers/",
    "1stopbabystore ltd": "https://www.onestop.co.uk/careers/",
    "2 Chai Ltd": "https://www.clintonhealthaccess.org/join-our-team/",
    "2023 RE INVESTMENT MANAGEMENT LIMITED": "https://uk.indeed.com/Investment-Management-Limited-jobs-in-London",
    "22 Hotel Management Limited": "https://uk.indeed.com/cmp/22-Hotel-Management-Ltd",
    "28 Trading Limited": "https://uk.indeed.com/q-28-trading-l-london-se18-jobs.html",
    "360 DIGI MARKETING LTD": "https://www.cv-library.co.uk/list-jobs/395687/360-Digi-Marketing-LTD-360-Digital-Marketing",
    "3A Care (London) Ltd": "https://uk.indeed.com/cmp/3a-Care-(london)-Limited",
    "3D BUILDING HOME LTD": "https://uk.indeed.com/q-3d-building-l-london-jobs.html",
    "3RD RAIL RESOURCE LTD": "https://3rdrailclothing.co.uk/jobs/",
    "3S Money Club Limited": "https://3s.money/careers",
    "4C EUROPE UK LTD": "https://www.4cstrategies.com/careers/",
    "4FEET RETAIL LTD": "https://uk.indeed.com/cmp/4feetshoes",
    "4M LONDON LIMITED": "https://www.4mgroup.co.uk/?FaqeID=9&n=27",
    "5 A DAY (LONDON) LTD": "https://www.cv-library.co.uk/remote-5-a-day-london-ltd-jobs-in-london",
    "500 Degrees Herne Hill Ltd": "https://uk.indeed.com/q-500-degrees-l-herne-hill-jobs.html",
    "53 Red Lion Ltd": "https://jobs.greeneking.co.uk/red-lion-drayton-jobs",
    "6 Degrees Capital LLP": "https://www.6dg.co.uk/work-with-us/",
    "6 Degrees Global Limited": "https://www.6dg.co.uk/work-with-us/",
    "6 TILL LATE LTD": "https://uk.indeed.com/q-6-till-late-jobs.html",
    "6sense Insights UK Ltd": "https://6sense.com/about-us/careers/join-us/",
    "7 HOPES LTD": "https://www.7hopes.co.uk/",
    "720 Management Limited": "https://uk.indeed.com/cmp/720-Management-Limited",
    "8668 Ltd T/A Rainbow Bridge": "https://www.niagarafallsbridges.com/employment-opportunities",
    "93digital": "https://93digital.co.uk/",
    "@ Home Accommodation Services Ltd": "https://uk.indeed.com/q-home-accommodation-services-l-london-n8-jobs.html",
    "A & A Himallari Ltd": "https://www.theaacareers.co.uk/",
    "A & M developer": "https://careers.alvarezandmarsal.com/en/",
    "A & S HAULAGE LTD": "https://uk.indeed.com/cmp/A-&-F-Haulage-Ltd-1",
    "A A HOMES AND HOUSING (PREMIER) LIMITED": "https://uk.indeed.com/cmp/Aa-Homes-and-Housing-Ltd",
    "A B HALAL LIMITED": "https://uk.indeed.com/q-have-halal-jobs.html",
    "A CLASS  NURSERY  LTD": "https://uk.indeed.com/q-a-class-nursery-jobs.html",
    "A Class Nursery Ltd": "https://uk.indeed.com/q-a-class-nursery-jobs.html",
    "A G & E S Ltd": "https://uk.indeed.com/q-a-g-&-e-s-jobs.html",
    "A G Supply Solutions Ltd": "https://uk.indeed.com/q-a-g-supply-solutions-jobs.html",
    "A Majeed Car paint": "https://uk.indeed.com/q-car-paint-shop-jobs.html",
    "A P Food Express": "https://uk.indeed.com/q-a-s-food-express-jobs.html",
    "A R VISION LIMITED": "https://uk.indeed.com/q-a-r-vision-l-london-wc1n-jobs.html",
    "A T & C PROFESSIONAL SYSTEMS LIMITED": "https://atandc.net/about/job-vacancies/",
    "A to Z Farsi Ltd": "https://www.hillintl.com/careers/",
    "A&A COMMUNICATION LTD": "https://www.theaacareers.co.uk/",
    "A&A ENTERPRISES LONDON LTD": "https://www.theaacareers.co.uk/",
    "A&B Building & Maintenance Ltd": "https://www.checkatrade.com/trades/aandbbuildingandmaintenance",
    "A&G LONDON PRIVATE LTD T/A SUBWAY": "https://www.subway.com/en-GB/careers",
    "A&M Capital Advisors Europe, LLP": "https://careers.alvarezandmarsal.com/en/",
    "A.A Automotive Dealership Limited": "https://www.theaacareers.co.uk/",
    "A.B. Hotels (The Arch London) Limited": "https://uk.indeed.com/q-arch-london-hotel-jobs.html",
    "A.L.S Hotels Limited t/a King Solomon Hotel": "https://uk.indeed.com/cmp/King-Solomon-Hotel",
    "A.S. Brill & Co Ltd": "https://brill.com/?language=en",
    "A.S.I. (Research) Limited": "https://asirecruitment.co.uk/",
    "A1 Woodgreen Retail Limited": "https://woodgreen.org.uk/faqs/i-am-interested-in-applying-for-a-job-or-want-an-update-on-my-application/",
    "A2Z CAR SOLUTIONS LTD": "https://uk.indeed.com/cmp/A-to-Z-Autoparts-Ltd",
    "A2Z CONSULTANCY LONDON LIMITED": "https://uk.indeed.com/cmp/A2z-Consultancy-London-Limited",
    "A2Z STAFFING SOLUTIONS LIMITED": "https://a2zstaffing.co.uk/join-the-team/",
    "AA & EVA LIMITED": "https://www.theaacareers.co.uk/",
    "AA AUTOMOTIVE SEAT COVERS LTD": "https://www.theaacareers.co.uk/",
    "AA Arts Limited": "https://www.theaacareers.co.uk/",
    "AA Car Fleet Ltd": "https://www.theaacareers.co.uk/",
    "AA ELECTRICAL AND MECHANICAL SERVICES LTD": "https://www.theaacareers.co.uk/",
    "AA Estate Agency Limited": "https://www.theaacareers.co.uk/",
    "AA Financial Bizz Limited": "https://www.theaacareers.co.uk/",
    "AA MERCHANT SERVICE LTD": "https://www.theaacareers.co.uk/",
    "AA Produce Limited": "https://www.theaacareers.co.uk/",
    "AA Retail Shops Ltd": "https://www.theaacareers.co.uk/",
    "AA4 Services Ltd": "https://www.theaacareers.co.uk/",
    "AABRU LIMITED": "https://uk.indeed.com/cmp/Abru-Ltd",
    "AB HOUSEHOLDS UK LIMITED": "https://www.abwalker.co.uk/about/careers/",
    "ABBAS MEAT LTD": "https://www.glassdoor.co.uk/job-listing/butcher-abbas-halal-meats-JV_IC3312271_KO0,7_KE8,25.htm?jl=1009341022322",
    "ABG SUNDAL COLLIER LIMITED": "https://www.abgsc.com/careers/",
    "ABI Interiors International Limited": "https://www.abiinteriors.co.uk/work-with-us/",
    "ABOVE & BEYOND CREATIVE LTD T/AS ABOVE + BEYOND": "https://aboveandbeyond.agency/",
    "ACADEMIC PLACEMENT SERVICES LTD": "https://www.academicsltd.co.uk/vacancies.asp",
    "ACCESS CARS LTD": "https://uk.indeed.com/q-access-cars-l-chislehurst-jobs.html",
    "ACCOUNTANCY & TAX SOLUTIONS (SW) LIMITED": "https://www.sw-au.com/careers/",
    "ACCOUNTANCY AND BOOKEEPING LIMITED": "https://www.accountancycareers.co.uk/",
    "ACCURA RESOURCING LIMITED": "https://www.accura.co.uk/we-are-recruiting/",
    "ACE Hotels Trading Ltd": "https://acehotel.com/careers/",
    "ACLI (CHRISTIAN ASSOCIATION OF ITALIAN WORKERS)": "https://register-of-charities.charitycommission.gov.uk/charity-search/-/charity-details/801109/contact-information",
    "ACTIVE OMG LIMITED": "https://omgukcareers.com/",
    "ACTIVE SPORTS TOURISM LTD": "https://uk.indeed.com/q-sports-tourism-jobs.html",
    "ACUITY KNOWLEDGE PARTNERS (UK) LIMITED": "https://www.acuitykp.com/careers/",
    "ADDISON LEE SERVICES LIMITED": "https://www.addisonlee.com/work-with-us-3/addison-lee-careers/",
    "ADF London Limited": "https://adfinternational.org/careers",
    "ADVERTTU LIMITED": "https://wellfound.com/company/adverttu",
    "AFTERS WALTHAMSTOW LTD": "https://uk.indeed.com/q-afters-ice-cream-l-walthamstow-central-station-jobs.html",
    "AG UK 2018 Limited": "https://www.cv-library.co.uk/list-jobs/420039/AG-UK-2018-LIMITED",
    "AIO LONDON LTD": "https://uk.indeed.com/All-in-One-London-jobs-in-London",
    "AIRLINEN LTD": "https://uk.indeed.com/cmp/Airlinen-Ltd",
    "AIS Consulting UK Ltd": "https://www.aisltd.com/careers/",
    "AISH HATORAH UK LIMITED": "https://about.aish.com/careers/",
    "AJI (RESTAURANTS) LIMITED": "https://uk.indeed.com/cmp/Aji-Restaurants-Ltd-1",
    "AJT Dimsum Limited": "https://www.pingpongdimsum.com/privacy/",
    "AKSAL UK LIMITED": "https://www.groupeaksal.com/en/carriere.html",
    "AKVP PROPERTIES LTD": "https://akvp-properties.co.uk/job-openings/",
    "AL AMAAN EDUCATION TRUST": "https://register-of-charities.charitycommission.gov.uk/charity-search/-/charity-details/5009341",
    "AL AMANA LTD T/A GREEN LEAF": "https://greenleafengineering.co.uk/vacancies/",
    "ALB ACCOUNTING LTD": "https://uk.indeed.com/cmp/Alb-Accounting-Ltd",
    "ALGHAD TV LIMITED": "https://uk.indeed.com/cmp/Al-Ghad-Tv",
    "ALPA CARE LTD": "https://www.alphahealthcaregroup.co.uk/work-with-us/",
    "ALYA LONDON LTD": "https://uk.indeed.com/q-alia-jobs.html",
    "AMF Medica Limited": "https://uk.indeed.com/q-a-m-f-medical-jobs.html",
    "AN Services ( Raynes Park) Ltd": "https://uk.indeed.com/l-raynes-park-jobs.html",
    "ANAYA INTERNATIONAL LTD": "https://uk.indeed.com/cmp/Anaya",
    "ANGEL1CA LTD": "https://angelicacrafthouse.com/work-with-us/",
    "ANISEED BAR & INDIAN RESTAURANT": "https://www.anisebar.com/careers/",
    "AO Brands International Limited": "https://www.ao-world.com/careers/",
    "AOE Logistics Limited": "https://ao-delivery.com/careers/",
    "AP Audit UK Limited": "https://uk.indeed.com/q-ap-audit-jobs.html",
    "APL Media Limited": "https://aplmedia.co.uk/careers/",
    "APLL UK LTD": "https://www.apllogistics.com/careers",
    "APM ACCOUNTANTS LIMITED": "https://www.apmaccountants.co.uk/",
    "APPLAUSE KONSULT LTD": "https://uk.indeed.com/cmp/Applause-Konsult-Ltd",
    "APPLEBY PROPERTIES LTD": "https://www.applebyglobal.com/careers/",
    "AQ1442 Ltd": "https://careers.next.co.uk/",
    "AQUA COMMS Management (UK) Limited": "https://aquacomms.com/careers/",
    "AR ASSETS PRIVATE LTD": "https://www.cv-library.co.uk/list-jobs/431817/AR-ASSETS-PRIVATE-LIMITED",
    "ARCH Venture Management UK Ltd": "https://www.archgroup.com/careers/",
    "ARHT Media (UK) Limited": "https://www.arht.tech/about/career/",
    "ARMIS SECURITY UK LIMITED": "https://www.armis.com/armis-careers/",
    "ART EVENTS AND MEDIA LTD": "https://www.artsjobs.org.uk/",
    "ART Group Services UK Limited": "https://www.artsjobs.org.uk/",
    "ARYA SAMAJ LONDON": "https://www.aryasamajlondon.org.uk/",
    "ARZANA LIMITED - T/A Pepe's": "https://uk.indeed.com/q-sale-pepe-jobs.html",
    "Aares Enterprise Ltd": "https://www.aresmgmt.com/about-ares-management-corporation/careers-at-ares",
    "Aaro Capital Limited": "https://en.aaro.capital/",
    "Abbey Tyres And Mechanic Limited": "https://abbeytyresandmechanic.co.uk/",
    "Abiglobal Foods Ltd": "https://uk.indeed.com/cmp/Abiglobal-Foods-Ltd-1",
    "Absolute Options UK Limited": "https://uk.indeed.com/m/jobs?q=Absolute+Options&l=London",
    "Academy of Motion Picture Arts and Sciences": "https://www.oscars.org/footer/careers",
    "Accel Capital Partners Ltd": "https://jobs.accel.com/jobs",
    "Accel Partners Management LLP": "https://jobs.accel.com/jobs",
    "Access Construct Ltd": "https://uk.indeed.com/q-access-construct-ltd-l-united-kingdom-jobs.html",
    "AccessData UK Limited": "https://uk.indeed.com/q-access-data-jobs.html",
    "Accor HotelServices UK Ltd": "https://careers.accor.com/global/en/ga-unitedkingdom",
    "Accor Luxury UK Limited": "https://careers.accor.com/global/en/ga-unitedkingdom",
    "Accor UK Business & Leisure Hotels Ltd": "https://careers.accor.com/global/en/ga-unitedkingdom",
    "Accor UK Limited": "https://careers.accor.com/global/en/ga-unitedkingdom",
    "Accord Europe Limited": "https://group.accor.com/en/careers",
    "Acer Tree Investment Management LLP": "https://www.acerim.com/",
    "Acinfo Limited": "https://www.glassdoor.co.uk/job-listing/graphic-designer-acinfo-limited-JV_IC2671300_KO0,16_KE17,31.htm?jl=1009375943618",
    "Acker U.K. Ltd.": "https://www.ackerwines.com/careers/",
    "Acorn Lodge Care Home": "https://uk.indeed.com/q-acorn-lodge-care-home-jobs.html",
    "Acrotrend Solutions Limited": "https://acrotrend.com/join-us/",
    "Active Retail (UK) Limited": "https://www.retailactive.com/join-us/",
    "Acton Muslim Welfare Association": "https://uk.indeed.com/q-muslim-l-acton-jobs.html",
    "Acts London": "https://www.artsjobs.org.uk/",
    "Actum International UK Limited": "https://actumllc.com/careers/",
    "Acuura Limited": "https://www.accura.co.uk/we-are-recruiting/",
    "Acxiom Limited": "https://www.acxiom.co.uk/careers/",
    "Ad Astra Bars Limited T\\A  The Three Crowns.": "https://www.thethreecrownsnottingham.co.uk/jobs",
    "Adamas Investment Holdings LLP": "https://www.adamsstreetpartners.com/careers/",
    "Adaptate Biotherapeutics Limited": "https://www.biotech-careers.org/company/adaptate-biotherapeutics",
    "Aderant Legal (UK) Limited": "https://www.aderant.com/careers-portal/",
    "Adjaye Associates Limited": "https://www.adjaye.com/contact/careers-2/",
    "Admiral Recruitment Limited": "https://www.admiraljobs.co.uk/",
    "Adonis Smart Foods Ltd": "https://uk.indeed.com/cmp/Adonis-Smart-Foods",
    "Adroitx Limited": "https://uk.indeed.com/cmp/Adroitx-Limited-1",
    "Adsum Technologies Ltd": "https://uk.indeed.com/cmp/Adsum",
    "Advance Shipping Limited": "https://uk.indeed.com/q-advance-shipping-jobs.html",
    "Advanced Payment Solutions": "https://aps.money/aps-careers/",
    "Advised Ltd": "https://www.adviceuk.org.uk/products-services/advicejobs/",
    "Adwuma Ltd": "https://uk.indeed.com/cmp/Adwuma-Care-Ltd",
    "Aeon Energy Ltd": "https://www.eon.com/en/about-us/careers.html",
    "Aermont Capital LLP": "https://www.aermont.com/",
    "Aerospace Technology Institute": "https://www.ati.org.uk/about-us/careers/",
    "Affiliate Intelligence": "https://openai.com/careers/",
    "Aflorithmic Labs, Ltd.": "https://wellfound.com/company/aflorithmiclabsltd",
    "Afro Beauty Centre Ltd": "https://uk.indeed.com/cmp/Afro-Hair-and-Beauty-Ltd",
    "Afsana Foods (UK) Ltd": "http://www.afsanafoods.co.uk/",
    "Aga Khan Foundation (United Kingdom)": "https://www.akf.org.uk/careers/",
    "Agency Delta Ltd": "https://deltabase.io/careers/",
    "Agenda 21 Architects Studio Ltd": "https://www.dezeenjobs.com/company/agenda-21-architects-studio/",
    "Agilico Workplace Technologies": "https://www.agilico.co.uk/careers/",
    "Agilisys Holdings Ltd": "https://www.agilisys.co.uk/careers/",
    "Agudas Israel Housing Association Ltd": "https://www.aiha.org.uk/contact-us/careers/",
    "Ai Beauty LTD": "https://www.ai-beauty.co.uk/career-opportunities/",
    "Aida Innovation Ltd": "https://www.aida-europe.com/en/hr/",
    "Aide Data Limited": "https://uk.indeed.com/q-data-assistant-jobs.html",
    "Aimlin Limited": "https://www.msamlin.com/en/about-us/careers.html",
    "Aiolos Bio Limited": "https://www.biotech-careers.org/company/aiolos-bio",
    "Air New Zealand Limited": "https://careers.airnewzealand.co.nz/",
    "Airfi Networks Services Limited": "https://wellfound.com/company/airfi-networks-uk-1",
    "Airport Retail Enterprises (UK) Ltd": "https://uk.indeed.com/cmp/Airport-Retail-Enterprises-(uk)-Limited-1",
    "Airportr Technologies Ltd": "https://airportr.com/en/",
    "Akuna Europe Limited": "https://akunacapital.com/careers",
    "Al Medina Foods Limited": "https://uk.indeed.com/cmp/Medina-Foods",
    "Al-Furqan Islamic Heritage Foundation": "https://al-furqan.com/",
    "Al-Khoei Foundation": "https://www.indeed.com/cmp/Al--khoei-Foundation",
    "Alasdair Cameron Limited": "https://www.camerongardens.co.uk/careers/",
    "Albatross CX LTD.": "https://www.cxg.com/careers/",
    "Alchemis Holdings Ltd": "https://www.alchemis.co.uk/join-us/",
    "Alcova Asset Management LLP": "https://alcovacap.com/",
    "Alexander Edward James Consulting Limited": "https://aejconsulting.com/",
    "Alexander Proudfoot (Europe) Ltd.": "https://proudfoot.com/careers/",
    "Alexander decor ltd": "https://alexanderdecor.co.uk/",
    "Algorithms Software UK Ltd": "https://uk.indeed.com/q-algorithms-software-uk-jobs.html",
    "Ali Cash and Carry": "https://www.aligroup.com/careers/",
    "Alison Education UK Ltd.": "https://alison.com/about/careers",
    "All Seasons Lettings Ltd": "https://uk.indeed.com/q-all-seasons-lettings-%26-management-jobs.html",
    "All2gether Limited": "https://2gethersupportsolutions.org/careers/",
    "Allen Lane Limited": "https://allenlane.co.uk/jobs/",
    "Allinonecare Limited": "https://www.allinonecare.co.uk/vacancies",
    "Allpets Veterinary Clinic": "https://www.allpetsvets.co.uk/about-us/join-the-team/",
    "Almaas London Limited": "https://uk.indeed.com/q-jewellery-l-london-jobs.html",
    "Almanax Ltd": "https://almanax.co.uk/en/services",
    "Alpargatas UK Limited": "https://alpargatas.com.br/jobs",
    "Alpha FX Limited": "https://www.alphagroup.com/about/careers/",
    "AlphaSense Technology Limited": "https://www.alpha-sense.com/careers/",
    "Alphawave IP Group PLC": "https://awavesemi.com/careers/",
    "Alphonso UK Limited": "https://uk.indeed.com/q-alphonso-jobs.html",
    "Alquity Investment Management Limited": "https://alquity.com/",
    "Altair Global Relocation Limited": "https://www.altairglobal.com/careers/",
    "Altis Global Limited": "https://altisconsulting.com/uk/join-altis/",
    "Altum Capital Management (UK) Ltd": "https://altumgroup.com/careers/",
    "Alula Insurtech Ltd": "https://alula.com/careers/",
    "Alula Technologies Ltd": "https://alula.com/careers/",
    "Amalgamated Laboratory Solutions limited": "https://als-dental.com/careers/current-vacancies/",
    "Amba Hotels (Oval) Limited T/A Belgrave Hotel": "https://www.the-belgrave.com/",
    "Ambassador Bakery Ltd": "https://uk.indeed.com/q-ambassador-bakery-jobs.html",
    "American International Church": "https://amchurch.co.uk/",
    "Amira G Foods Ltd": "https://www.amira.net/careers/",
    "Amitis Partners Limited": "https://e2exchange.com/e2e_directory/amitis-partners/",
    "Amnesty International, International Secretariat": "https://www.amnesty.org/en/careers/",
    "Amorigin Limited": "https://www.imo.org/en/About/Careers/Pages/default.aspx",
    "Amory London Ltd": "https://uk.indeed.com/cmp/Amory-London",
    "Amrutha Catering Ltd": "https://uk.indeed.com/cmp/Amrutha-Catering-Ltd",
    "Amtex Solutions Limited": "https://amtexsystems.jobs.net/",
    "An Easy Visa Limited": "https://www.aneasyvisa.co.uk/",
    "Anaconda Services (UK) Limited": "https://www.anaconda.com/about-us/careers",
    "Anglican Consultative Council": "https://www.anglicancommunion.org/structures/anglican-communion-office/vacancies.aspx",
    "Anglo Assemble Limited": "https://uk.angloamerican.com/careers",
    "Anglo Chinese School of London Limited": "https://www.acs-schools.com/working-at-acs/vacancies/",
    "Anglo Galleon International Ltd": "https://anglo-galleon.com/",
    "Anglo Indian Beverage Ltd": "https://www.cv-library.co.uk/list-jobs/433228/Anglo-Indian-Beverage-Ltd",
    "Anglo Pacific International Limited": "https://www.anglopacific.co.uk/careers.htm",
    "Anika Fruit & Veg Ltd": "https://anika.com/join-anika/careers/",
    "Anondo Bazar Ltd T/A Anondo Bazar": "https://in.indeed.com/cmp/Abp-Pvt.-Ltd-(anandabazar-Patrika)",
    "Anshi Ltd T/A Subway": "https://www.subway.com/en-GB/careers",
    "Anthesis (UK) Limited": "https://www.anthesisgroup.com/careers/",
    "Antico Ltd": "https://uk.indeed.com/cmp/Antico-Ltd-1",
    "Aplomb Childcare Limited": "https://www.aplombdaynursery.com/",
    "Apphere Ltd": "https://careers.next.co.uk/",
    "Aptem Ltd": "https://www.aptem.co.uk/work-for-us/",
    "Aqua Fun Ltd": "https://www.indeed.com/m/jobs?q=Aqua+Fun+Pools",
    "Aqua Security Software UK LTD": "https://www.aquasec.com/about-us/careers/",
    "Ar world ltd": "https://uk.indeed.com/q-ar-world-l-ilford-jobs.html",
    "Arachnys Information Services Limited": "https://www.arachnys.com/author/user/",
    "Araz Farm Feed Ltd": "https://uk.indeed.com/cmp/Araz-Farm-Feed-Ltd",
    "Arcadis Human Resources Limited": "https://careers.arcadis.com/",
    "Arch Insurance (UK) Limited": "https://www.archgroup.com/careers/insurance/",
    "Archangel Clinic Ltd": "https://www.archangelclinic.co.uk/",
    "Architecture for London": "https://www.dezeenjobs.com/company/architecture-for-london/",
    "Arcus Infrastructure Services LLP": "https://arcusip.com/",
    "Ares Management Limited": "https://www.aresmgmt.com/about-ares-management-corporation/careers-at-ares",
    "Areteans Technology Solutions UK Limited": "https://areteanstech.com/careers/",
    "Argent (Property Development) Services LLP": "https://relatedargent.co.uk/",
    "Argo Natural Resources Limited": "https://www.argolimited.com/careers/",
    "Ark Investment Management Ltd": "https://www.ark-invest.com/work-at-ark",
    "Arnold & Porter Kaye Scholer (UK) LLP": "https://www.arnoldporter.com/en/careers",
    "Arome Central Ltd": "https://uk.indeed.com/q-pastry-bakery-l-greater-london-jobs.html",
    "Arrow International Media Limited": "https://www.arrowmedia.com/contact",
    "Arrows Group Professional Limited": "https://arrowsgroup.com/jobs/",
    "Art Africa Ltd": "https://uk.indeed.com/q-art-africa-jobs.html",
    "Art And Industry Ltd": "https://www.artsjobs.org.uk/",
    "Art Services Grants Ltd": "https://www.artscouncil.org.uk/jobs-and-careers",
    "Art of the Puppet Ltd": "https://www.artscouncil.org.uk/jobs-and-careers",
    "Artek Group Plc": "https://artek.uk/careers",
    "Artemis Investment Management LLP": "https://www.artemisfunds.com/en/about-artemis/careers",
    "Artemis Origination Limited": "https://www.artemisfunds.com/en/about-artemis/careers",
    "Artemisia Global Capital Limited": "https://www.artemisfunds.com/en/about-artemis/careers",
    "Artis Finance Limited": "https://www.artisrecruitment.co.uk/careers/",
    "B J I Limited T/A Montana Hotel & Light of India": "https://montanahotel.co.uk/",
    "B&B Hotels UK Limited": "https://www.hotel-bb.com/en/company/spain/our-job-offers",
    "B'NAI B'RITH HILLEL FOUNDATION t/a Union of Jewish Students": "https://www.hillel.org/work-at-hillel/",
    "B.P. Marsh & Partners Plc": "https://www.bpmarsh.co.uk/",
    "BABA COURIERS LTD": "https://uk.indeed.com/q-couriers-jobs.html?start=60",
    "BABACIK LTD": "https://www.babcockinternational.com/careers/",
    "BAE Healthcare Limited": "https://www.baesystems.com/en/careers",
    "BANANA ISLAND BAR AND RESTAURANT": "https://uk.indeed.com/cmp/Banana-Island-Bar-and-Restaurant-1",
    "BANK NEGARA MALAYSIA (LONDON REPRESENTATIVE OFFICE)": "https://www.bnm.gov.my/careers",
    "BARKING SALON LIMITED": "https://uk.indeed.com/q-beauty-salon-l-barking-and-dagenham-jobs.html",
    "BARRICK GOLD (LONDON) LTD": "https://www.barrick.com/English/careers/default.aspx",
    "BARTON HUXLEY MANAGEMENT LTD": "https://www.huxley.com/en-gb/about/careers/",
    "BAYATI SERVICES LIMITED": "https://www.glassdoor.co.uk/job-listing/picker-and-packer-bayati-services-JV_IC2671300_KO0,17_KE18,33.htm?jl=1009291770895",
    "BBP Express Ltd": "https://www.yell.com/biz/bbp-express-ltd-greenford-9583689/",
    "BCI UK IRR Limited": "https://careers.thebci.org/",
    "BCL Management and Consultancy Ltd": "https://uk.indeed.com/cmp/Bcl-Management-&-Consultancy-Ltd/salaries/Office-Administrator",
    "BEAUTY LOUNGE (HINCKLEY) LTD": "https://uk.indeed.com/q-beauty-salon-l-hinckley-jobs.html",
    "BEAUTYBOX MARKET LIMITED": "https://uk.indeed.com/q-beauty-box-jobs.html",
    "BEBETTO UK LTD": "https://www.bebeto.co.uk/",
    "BECONTREE HOMES LTD": "https://uk.indeed.com/l-becontree-jobs.html",
    "BEHAVIOURAL INSIGHTS LTD": "https://www.bi.team/about-us/careers/",
    "BEIER360 Limited": "https://uk.indeed.com/cmp/Beier360-Limited-2",
    "BELIEVE SUPPORTED LIVING LIMITED": "https://uk.indeed.com/q-believe-supported-living-jobs.html",
    "BENJI'S BUNS LIMITED": "https://uk.indeed.com/cmp/Benji%27s-Buns",
    "BERMONDSEY ENGINEERING & TRADE CO. LTD": "https://uk.indeed.com/m/jobs?q=Engineering&l=Bermondsey",
    "BEST AT LESS STORE LTD": "https://www.elcompanies.co.uk/en-gb/careers",
    "BEST IN CITY LTD": "https://uk.indeed.com/q-best-in-city-limited-l-london-jobs.html",
    "BETHEL MINI MART LIMITED T/A BETHEL MINI MART": "https://uk.indeed.com/cmp/Mini-Mart",
    "BEXLEYHEATH COFFEE LTD": "https://uk.indeed.com/q-coffee-l-bexleyheath-jobs.html",
    "BG EXPRESS LIMITED T/A BG EXPRESS": "https://www.jobs.bg/en/terms.php?type=2",
    "BG&E Consulting Engineers Ltd": "https://bgeeng.com/career/",
    "BHA Trading Limited": "https://www.britishhorseracing.com/work-bha/bha-vacancies/",
    "BIG BEN BUTCHERY LTD": "https://butcherycareers.co.uk/",
    "BILLINGSGATE FRESH FISH LTD": "https://uk.indeed.com/cmp/Billingsgate-Fresh-Fish-Ltd",
    "BK SENOL LTD": "https://www.simplyhired.co.uk/job/nBQlJ8PeACXiuJhmETjdco8IKIgxP7b_xekUlc4p8LGUpdIfRC4Fvw",
    "BK Shipping Ltd": "https://www.bkfreight.co.uk/",
    "BLOOM HEALTH GROUP LTD": "https://bloom.health/careers/",
    "BLOOMING SCENT LIMITED": "https://uk.indeed.com/cmp/Blooming-Scent-Caf%C3%A9",
    "BLS DEVELOPMENT AND CONSTRUCTION LIMITED": "https://www.bls.ch/en/unternehmen/jobs-und-karriere/offene-stellen",
    "BLUE ALPINE PARTNERS LIMITED T/A BLUE ALPINE": "https://www.bluealpine.com/",
    "BLUE SKY DEVELOPERS LIMITED": "https://www.cv-library.co.uk/list-jobs/260063/Blue-Sky-Developers",
    "BLUX CONSULTANCY LIMITED": "https://blu-tech.co.uk/",
    "BMD Infrastructure Services Limited": "https://bmdinfrastructureservices.co.uk/",
    "BMI Healthcare Limited trading as Circle Health Group Limited": "https://careers.circlehealthgroup.co.uk/",
    "BNTL Care Limited (Trading as Summerdale Court Care Home)": "https://lukkahomes.com/summerdale-court-care-home/",
    "BOLD INNOVATE LTD": "https://www.bold.com/bold-jobs/",
    "BOMBAY SPICY LIMITED": "https://uk.indeed.com/cmp/Bombay-Spice",
    "BONBON POTTERY LTD": "https://www.bonbonpottery.co.uk/jobs/",
    "BOND180 LIMITED": "https://wellfound.com/company/bond180",
    "BONNEY OIL AND GAS LTD": "https://www.bonneyenergy.com.au/careers/",
    "BOOKING.COM LIMITED": "https://careers.booking.com/",
    "BOW PIZZA LIMITED": "https://uk.indeed.com/Pizza-jobs-in-Bow",
    "BQC (WOODGREEN) LTD": "https://woodgreen.org.uk/faqs/i-am-interested-in-applying-for-a-job-or-want-an-update-on-my-application/",
    "BRANDA LTD": "https://pentlandbrands.com/careers/",
    "BRG INFOTECH LIMITED": "https://www.brginfotech.co.uk/careers",
    "BRILLANCE UK LIMITED": "https://careers.rolls-royce.com/united-kingdom",
    "BSB Construction Ltd": "https://www.bsbstructural.co.uk/about-us/vacancies/",
    "BSK Traders Limited": "https://uk.indeed.com/q-bsk-traders-jobs.html",
    "BUDDHA LOUNGE LONDON LTD": "https://uk.indeed.com/cmp/Buddha-Lounge",
    "BULANDI LTD": "https://ca.indeed.com/cmp/Bulandi-Wood-Design-Ltd.",
    "BUSINESS MANAGEMENT LONDON LIMITED": "https://uk.indeed.com/q-business-management-l-london-jobs.html",
    "BW Epic Kosan (UK) Limited": "https://bwek.com/careers/",
    "Babcock Defence & Security Holdings LLP": "https://www.babcockinternational.com/careers/",
    "Babel Public Relations Limited": "https://babelpr.com/working-at-babel/",
    "Baily Garner LLP": "https://www.bailygarner.co.uk/careers/",
    "Baird & Co Limited": "https://bairdcareers.com/",
    "Bake Street Limited": "https://uk.indeed.com/l-baker-street-jobs.html",
    "Balbec Capital Limited": "https://balbec.com/",
    "Balham Park Surgery": "https://www.balhamparksurgery.co.uk/",
    "Balham Retailers Limited": "https://uk.indeed.com/m/jobs?q=Retail&l=Balham",
    "Baltic Pets Ltd": "https://www.balticapprenticeships.com/baltic-careers/",
    "Bank of London and The Middle East Plc": "https://www.blme.com/about-us/working-for-blme/",
    "Bar Salon": "https://uk.indeed.com/q-hair-bar-l-london-jobs.html",
    "Barilla Acceleration Limited": "https://www.barillagroup.com/en/careers/",
    "Barilla International Limited UK": "https://www.barillagroup.com/en/careers/",
    "Baruch Enterprises Ltd": "https://uk.indeed.com/cmp/Baruch-Enterprises-Ltd",
    "Basware Holdings Ltd": "https://careers.basware.com/",
    "Battersea Chef LTD": "https://uk.indeed.com/q-chef-l-battersea-jobs.html",
    "Battersea Fields Practice": "https://www.batterseafieldspractice.co.uk/practice-information/vacancies/",
    "Bayforest Technologies Limited": "https://bayforest.ai/careers/",
    "Bayleaf Restaurant Ltd": "https://uk.indeed.com/cmp/Bayleaf-Restaurant",
    "Bayview International UK Ltd": "https://bayview.com/careers/",
    "Beacon Platform Limited": "https://www.beacon.io/careers/",
    "Beauchamp Hospitality Ops Ltd": "https://uk.indeed.com/m/jobs?q=Beauchamps",
    "Beautiful Tracking Limited": "https://www.elcompanies.co.uk/en-gb/careers",
    "Beauty and Focus(UK) Ltd": "https://www.elcompanies.co.uk/en-gb/careers/apply",
    "Beautyworld Cosmetics (UK) Ltd": "https://uk.indeed.com/m/jobs?q=Beauty+World",
    "Bebek Istanbul Ltd": "https://www.glassdoor.com/Job/bebek-jobs-SRCH_IL.0,5_IC3361422.htm",
    "Beech Haven Ltd": "https://jobs.haven.com/",
    "Begbies Chartered Accountants": "https://www.begbiesaccountants.co.uk/careers/",
    "Benda Bili Ltd T/A Sezane": "https://www.sezane.com/ca/join-the-team",
    "Bengal Spice Euro Limited T/A Cafe Grill": "https://uk.indeed.com/cmp/Bengal-Spice",
    "Bensussen Deutsch & Associates Limited": "https://www.bdainc.com/careers/",
    "Bentley Systems (UK) Ltd": "https://www.bentley.com/company/careers/",
    "Berkeley Research Group (UK) Limited": "https://www.thinkbrg.com/careers/",
    "Berry Palmer & Lyle Limited": "https://bpl-insurance.com/our-team/careers/",
    "Bespoke Kitchens Solutions Limited": "https://uk.indeed.com/q-bespoke-kitchen-solutions-jobs.html",
    "Best & Fast Body Work Limited": "https://uk.indeed.com/Car-Body-Work-Repair-jobs",
    "Best Fish Bazar": "https://www.thefishmarket.com/careers/",
    "Best Glazing Limited": "https://www.bestdoubleglazing.co.uk/",
    "Best Price News Agent": "https://uk.indeed.com/q-newsagents-jobs.html",
    "Best Wines London Ltd": "https://bestwines.co.uk/",
    "Best4business Accountants & Company Limited": "https://best4business.com/careers/",
    "Bestrustees Limited": "https://www.bestrustees.co.uk/join-us/",
    "Betbull Social Sports UK Limited": "https://uk.indeed.com/cmp/Betbull",
    "Bettina Looney Ltd": "https://uk.indeed.com/cmp/Bettina-Looney-Ltd/salaries",
    "Bibs Polishers Jewellery Workshop LLP": "https://www.bibspolishers.co.uk/",
    "Bickiepegs Healthcare Limited": "https://www.bickiepegs.com/",
    "Bidvest Noonan": "https://bidvestnoonan.co.uk/careers/",
    "Bier Nuts Limited": "https://uk.indeed.com/cmp/Bier-Nuts",
    "Bijaya Ltd t/a Munal Tandoori": "https://www.munaltandoori.co.uk/vacancy/",
    "Bijoy Youth Group": "https://register-of-charities.charitycommission.gov.uk/charity-details/?regid=1075206&subid=0",
    "Bike Taxi Limited (T/A Pedal Me)": "https://pedalme.co.uk/work-with-us",
    "Bikeworks": "https://www.bikeworks.org.uk/join-our-team/",
    "Birth London Limited": "https://uk.indeed.com/q-the-birth-company-l-london-jobs.html",
    "Biscuiteer Baking Company Ltd": "https://www.biscuiteers.com/vacancies",
    "Bistro 24 Ltd": "https://www.indeed.com/cmp/Bistro-24",
    "Bisushima Japanese Restaurant": "https://uk.indeed.com/cmp/Bisushima-1",
    "Black Swan Capital": "https://blackswanfp.co.uk/careers/",
    "Black Temple Limited": "https://www.templegroup.co.uk/careers/",
    "Blackfriars Hotels Limited": "https://uk.indeed.com/q-blackfriars-hotel-l-london-jobs.html",
    "Blacklion Law LLP": "https://uk.indeed.com/cmp/Blacklion-Law-LLP",
    "Blackstock Dental Care": "https://uk.indeed.com/cmp/Blackstock-Dental-Care",
    "Blend Media Ltd": "https://blend.media/careers/",
    "Blevins Franks Wealth Management Limited": "https://www.blevinsfranks.com/who-we-are/careers/",
    "Blow Beauty Ltd": "https://uk.indeed.com/cmp/Blow-Ltd",
    "Blue Ant International Limited": "https://blueantmedia.com/about-us/careers/",
    "Blue Building Services Ltd": "https://uk.indeed.com/q-blue-building-services-ltd-jobs.html",
    "Blue Skies Space Ltd.": "https://bssl.space/careers/",
    "Blue tech IT Ltd": "https://blu-tech.co.uk/",
    "BlueFloat Management UK Limited": "https://www.bluefloat.com/careers/",
    "BlueShift Online Limited": "https://blueshift.com/jobs/",
    "Bluet Productions Ltd.": "https://blueantmedia.com/about-us/careers/",
    "BoPubCo": "https://www.huboo.com/careers/",
    "Bobrick Washroom Equipment Limited": "https://www.bobrick.com/about-us/careers/",
    "Boilersafe Services Limited": "https://www.boiler-safe.co.uk/",
    "Boldhaven Management LLP": "https://boldhaven.com/",
    "Bonham and Brook": "https://bonhamandbrook.co.uk/careers/",
    "Border Crossings": "https://careers.homeoffice.gov.uk/role/frontline-and-operational/border-force",
    "Bornoa Limited": "https://uk.indeed.com/cmp/Borno-Chemists-Ltd",
    "Bottega Prelibato Limited": "https://uk.indeed.com/cmp/Bottega-Prelibato",
    "Bow Street Hotel Limited": "https://www.hilton.com:443/en/hotels/lonnmnd-nomad-london/",
    "Bow Wow London Limited": "https://uk.indeed.com/cmp/Bow-Wow-London",
    "Box.com (UK) Limited": "https://careers.box.com/",
    "Braemar ACM Shipbroking Limited": "https://braemar.com/careers/",
    "Brain Source International Limited": "https://brain-source.com/",
    "Brand Communication Creatives UK Ltd": "https://brandcommsgroup.com/",
    "Brand Design Hub LTD": "https://www.upwork.com/agencies/1381945156568231936/",
    "Brent, Wandsworth and Westminster Mind": "https://www.bwwmind.org.uk/mind-jobs-in-london/",
    "Brett Wilson LLP": "https://www.brettwilson.co.uk/careers/",
    "Brickendon Consulting Limited": "https://www.brickendon.com/careers/",
    "Bridgeman Art Library Ltd t/a Bridgeman Images": "https://www.bridgemanimages.com/en/about/careers",
    "BrightSign Technology Limited": "https://www.brightsign.biz/about/careers/",
    "Brighton London Road Vision Plus Limited TA Brighton London Road Specsavers Limited": "https://www.specsavers.co.uk/stores/brightonlondonroad",
    "Brillio Technologies Private Limited": "https://careers.brillio.com/",
    "Brinkworth Design Limited": "https://www.dezeenjobs.com/company/brinkworth/",
    "British Academy": "https://www.thebritishacademy.ac.uk/about/jobs/",
    "British Academy of Jewellery Ltd": "https://baj.ac.uk/work-at-baj/",
    "British International Investment plc": "https://www.bii.co.uk/en/careers/vacancies/",
    "British Water": "https://www.britishwater.co.uk/",
    "Britzke Nutrition Ltd.": "https://raquelbritzke.co.uk/",
    "Brixton Hill Group Practice": "https://www.brixtonhillgp.nhs.uk/3793-2/",
    "Bronzemarch Trading Limited T/A Hare and Tortoise": "https://www.hareandtortoise.co.uk/assets/pdf/privacy_policy.pdf",
    "Brook House Care Ltd": "https://uk.indeed.com/q-brook-house-care-home-jobs.html",
    "Broom House 39/43 London Road": "https://absolute.digital/company/careers/",
    "Broome End Ltd": "https://uk.indeed.com/cmp/Broome-End-Care-Home",
    "Brown & Brown (Europe) Limited": "https://www.bbinsurance.com/careers/",
    "Browns (South Molton Street) Limited": "https://www.brownsfashion.com/careers/senior-personal-shopper",
    "Bruton Bond Limited": "https://www.brutoncapital.com/careers/",
    "Buchanan Communications": "https://www.buchanan.com/careers/",
    "Buck Consultants Limited": "https://buck.com/ca/",
    "Budget Energy": "https://budgetenergy.co.uk/about/careers",
    "Business Skills Interactive Limited": "https://jobs-portal.co.uk/business-skills/",
    "Business Systems International Ltd.": "https://www.bsi.uk.com/who-are-we/careers",
    "Button Tech UK Limited": "https://uk.indeed.com/cmp/Button-Tech-UK-Limited-1",
    "C.Gars Ltd": "https://uk.indeed.com/cmp/C.gars-Ltd",
    "C.V. A.C LIMITED": "https://uk.indeed.com/cmp/C.v.a.c-Ltd?campaignid=mobvjcmp&from=mobviewjob&tk=1i2caok37ktaq806&fromjk=0b4a12177d3a20e0",
    "CACI Limited": "https://www.caci.co.uk/careers/",
    "CADA Design Group Ltd": "https://www.cada.co.uk/careers/",
    "CALABASH LOGISTICS LTD": "https://uk.indeed.com/cmp/Calabash-Logistics-Ltd",
    "CAMDEN COMMUNITY FOOTBALL AND SPORTS ASSOCIATION": "https://www.camden.gov.uk/jobs-camden-council",
    "CANADA London Ltd": "https://www.canadalife.co.uk/our-company/careers/",
    "CANFIELDS LAW LIMITED": "https://www.canfieldslaw.co.uk/",
    "CAPITAL BUTCHER LTD": "https://butcherycareers.co.uk/",
    "CARD TRANSACT LIMITED": "https://www.transact-online.co.uk/working-at-transact/",
    "CARE PESPECTIVE LTD": "https://careperspectives.co.uk/career/",
    "CARE-AWAY LIMITED trading as CARE SUPPORT": "https://uk.indeed.com/cmp/Care-Away-Limited",
    "CARE4UHOMECARE LTD": "https://uk.indeed.com/cmp/Care4uhomecare-Ltd",
    "CARIBBEAN CLASSIC LTD": "https://uk.indeed.com/q-caribbean-restaurant-jobs.html",
    "CARIBEAN FOODS LTD": "https://www.island-delight.co.uk/careers/",
    "CARING FEATHERS LTD": "https://uk.indeed.com/cmp/Caring-Feathers-Ltd",
    "CARPET DIRECT TRADERS LTD": "https://www.checkatrade.com/trades/carpetdirecttradersltd",
    "CATERING & CLEANING SOLUTIONS LTD": "https://uk.indeed.com/q-catering-&-cleaning-solutions-jobs.html",
    "CATERLAND HOSPITALITY LTD TRADING AS CHOURANGI": "https://chourangi.co.uk/careers/",
    "CAZOO LTD": "https://cazoo.co.uk/",
    "CBRE Limited": "https://www.cbre.co.uk/careers",
    "CDW Limited": "https://ukcareers.cdw.com/",
    "CE Europe Ltd": "https://uk.indeed.com/Ce-Europe-jobs",
    "CEDAR HOUSE (KENT) LIMITED": "https://uk.indeed.com/cmp/Cedar-House",
    "CEF GROUP (UK) LIMITED": "https://www.cef.co.uk/careers/information",
    "CFGI (UK) Limited": "https://www.cfgi.com/careers/",
    "CGMS LONDON LTD": "https://www.cma-cgm.com/local/united-kingdom/job-opportunities",
    "CHA SHA HOUNSLOW LTD": "https://chasha.co.uk/careers/",
    "CHAKRA CEM LTD": "https://uk.indeed.com/CEM-jobs",
    "CHARLTON AUTO REPAIR CENTRE LIMITED": "https://uk.indeed.com/q-mechanic-l-charlton-jobs.html",
    "CHEEKY VAN LIMITED": "https://uk.indeed.com/m/jobs?q=Cheeky",
    "CHEF STEAKHOUSE LTD": "https://uk.indeed.com/q-steak-house-chef-jobs.html",
    "CHESTERS (WOOD GREEN) LIMITED": "https://woodgreen.org.uk/faqs/i-am-interested-in-applying-for-a-job-or-want-an-update-on-my-application/",
    "CHINGFORD FABRIC CARE LTD": "https://uk.indeed.com/q-sewing-l-london-jobs.html",
    "CHINGFORD TYRES LIMITED": "https://uk.indeed.com/Tyre-Technician-jobs-in-Chingford",
    "CHRIST APOSTOLIC CHURCH (GOSPEL GENERATION0": "https://oscar.org.uk/opportunities/viewall",
    "CHRIST APOSTOLIC CHURCH BALM OF GILEAD CHRISTIAN MINISTRIES INTERNATIONAL": "https://register-of-charities.charitycommission.gov.uk/charity-search/-/charity-details/3985974/full-print",
    "CHRIST APOSTOLIC MISSION CHURCH (JOY OF SALVATION)": "https://register-of-charities.charitycommission.gov.uk/charity-search/-/charity-details/5013249",
    "CHRIST MIRACLE CHURCH MISSION": "https://www.cmcm-worldwide.org/",
    "CHRIST REFORMED INTERNATIONAL MINISTRIES": "https://oscar.org.uk/opportunities/viewall",
    "CIAO CIAO ITALIA LIMITED": "https://uk.indeed.com/cmp/Ciao-Italia",
    "CIGMA CONSTRUCTION LTD": "https://www.sigmagrp.co.uk/company/careers/",
    "CINEDREAMFILMS LTD": "https://careers.cineworld.co.uk/",
    "CITI KITCHEN LONDON LIMITED": "https://www.citikitchenuk.com/",
    "CITY MAX INTERNATIONAL LTD": "https://uk.indeed.com/cmp/City-Max-International-Ltd",
    "CJ Foods Sales UK, Ltd": "https://uk.indeed.com/q-cj-foods-sales-jobs.html",
    "CK Morgan Ltd": "https://uk.indeed.com/cmp/Ck-Morgan-Limited",
    "CLIMAX CUISINE LTD T/a Magic Wok & Box": "https://uk.indeed.com/cmp/Magic-Wok",
    "CM Delta Ltd": "https://uk.indeed.com/cmp/Cm-Delta-Ltd",
    "CMT CONSTRUCTION MATERIAL TRADING LTD": "https://cmtconstruction.co.uk/career/",
    "CMT Design & Construction Ltd": "https://cmtconstruction.co.uk/career/",
    "COBALT ME FZE": "https://www.sage.com/en-gb/company/careers/",
    "COFCO (UK) LIMITED": "https://www.cofcointernational.com/careers/",
    "COLOSSAL ENTERPRISES LIMITED": "https://colossal.com/careers/",
    "COLOUR CHEM UK LIMITED": "https://uk.indeed.com/q-colour-chemistry-jobs.html",
    "COLOURMATCH DECORATOR CENTRE LIMITED": "https://dulux.manpower.co.uk/",
    "COMFOTEL HOTELS LLP": "https://group.accor.com/en/careers",
    "CONNOR CLARK & LUNN UK LIMITED": "https://cclfg.cclgroup.com/careers/opportunities/",
    "CONTINENTAL COMMERCIAL GROUP LIMITED": "https://www.continental.com/en/career/",
    "CONTRACTPOD TECHNOLOGIES LIMITED": "https://contractpodai.com/careers/",
    "CORNERSTONE VENTURE PARTNERS LLP": "https://careers.cornerstonevc.co/jobs",
    "CORTI AI UK LIMITED": "https://www.careers.corti.ai/",
    "CQS (UK) LLP": "https://www.cqs.com/careers",
    "CRA International (UK) Limited": "https://www.crai.com/cra-careers/jobs/",
    "CRAYDAWN PENDLEY MANOR LIMITED": "https://www.pendley-manor.co.uk/careers/",
    "CRCCD LEX LTD": "https://solicitors.lawsociety.org.uk/office/565913/crccd-lex-ltd",
    "CRESTA SOLUTIONS LIMITED": "https://cresta.com/careers/",
    "CRH Group Limited": "https://www.crh.com/careers",
    "CRYSTAL NAMAK LTD": "https://maldonsalt.com/careers/",
    "CTC HOLDING LIMITED": "https://ctcglobal.com/careers/",
    "CURIS HEALTHCARE INVESTMENTS LTD": "https://www.curis.com/careers/open-positions/",
    "CURRENTSPACE LTD": "https://www.featurespace.com/careers/current-opportunities/",
    "CUTMASTER BARBER SHOP": "https://caernarfon.cylex-uk.co.uk/company/cutmaster-barber-shop-27397390.html",
    "CUTPRICE STORE LIMITED": "https://uk.indeed.com/Cut-Price-jobs",
    "CWF & Partners Ltd": "https://cwfpartners.co.uk/vacancies/",
    "Cadmus International UK Limited": "https://cadmusgroup.com/careers/",
    "Cafe Grove Park": "https://uk.indeed.com/m/jobs?q=Cafe&l=Grove+Park",
    "Cake Inn London Ltd": "https://cakeinn.co.uk/",
    "Calm.com (GB) Limited": "https://www.calm.com/careers/",
    "Cambridge Nursing Home": "https://uk.indeed.com/q-cambridge-nursing-home-l-wanstead-jobs.html",
    "Capital Arches Group Ltd": "https://uk.indeed.com/cmp/Capital-Arches-Group-Ltd",
    "Capital Computer Software Ltd": "https://uk.indeed.com/q-capital-computer-software-jobs.html",
    "Capital Consulting International Ltd.": "https://cci-int.com/careers-with-cci/",
    "Capital Fund Management LLP": "https://www.cfm.com/join-us/",
    "Capital Hotels Ltd": "https://thecapital.co.za/careers/",
    "Capitol Catering Equipment LTD": "https://uk.indeed.com/Capital-Catering-jobs",
    "Caplin Systems Limited": "https://www.caplin.com/business/careers",
    "Cardtronics UK Limited": "https://uk.indeed.com/cmp/Cardtronics-Uk-Ltd",
    "Care By Mail Limited": "https://uk.indeed.com/q-care-by-mail-jobs.html",
    "Career Tutors Limited": "https://www.careertutors.co.uk/careers",
    "Caretower Ltd": "https://uk.indeed.com/cmp/Caretower",
    "Cargostore Worldwide Trading Ltd": "https://cargostore.com/recruitment-2022/",
    "Carma International Limited": "https://carma.com/join-the-team/",
    "Carta Financial Services Limited": "https://carta.com/careers/",
    "Carterhatch Homes LTD": "https://uk.indeed.com/cmp/Carterhatch-House-Children's-Residential-Care-Home/salaries?job_category=education&location=GB%2FENG%2FGTL%2FNorth+London",
    "Cask Industries Ltd": "https://casknx.com/cask-careers/",
    "Casse Croute": "https://uk.indeed.com/cmp/Casse--cro%C3%BBte-3",
    "Castleforge Partners Limited": "https://castleforge.com/careers/",
    "Catalyst Marketing Services Ltd": "https://www.wearecatalyst.co.uk/careers/",
    "Caxton Europe Asset Management Limited": "https://www.caxton.com/careers/",
    "Ceek Group Ltd": "https://ceek.co.uk/careers/",
    "Celebration Meal Limited": "https://uk.indeed.com/Celebrations-Ltd-jobs",
    "Celestial Church Beulah Wonderful Parish": "https://register-of-charities.charitycommission.gov.uk/charity-search/-/charity-details/5049746/contact-information",
    "Celestial Church of Christ Aduragbemi (Power of Prayer) Parish": "https://register-of-charities.charitycommission.gov.uk/charity-search/-/charity-details/3986073",
    "Celestial Church of Christ Revelation of Hope Parish": "https://register-of-charities.charitycommission.gov.uk/charity-search/-/charity-details/5167497/contact-information",
    "Celestial Globe Group Ltd": "https://uk.indeed.com/cmp/Celestial-Globe-Group-Ltd",
    "Center for Creative Leadership Ltd": "https://www.ccl.org/about-us/careers/",
    "Center for Global Development Europe": "https://www.cgdev.org/careers",
    "CenterSquare Investment Advisors UK Ltd": "https://www.centersquare.com/careers/",
    "Centerbridge Partners Europe, LLP": "https://www.centerbridge.com/culture-and-careers/",
    "Central Health Holdings Ltd": "https://centralhealth.org.uk/careers/",
    "Central Ridge Partners LLP": "https://ridge.co.uk/careers/",
    "Central coffee limited": "https://uk.indeed.com/q-central-coffee-l-solihull-b90-jobs.html",
    "Centre For Policy Studies Limited": "https://cps.org.uk/about/vacancies/",
    "Centre for Finance, Technology and Entrepreneurship Ltd": "https://courses.cfte.education/about-us/fintech-jobs/",
    "Centre for Mental Health": "https://www.centreformentalhealth.org.uk/about-us/jobs/",
    "Centricus Asset Management Limited": "https://www.centricus.com/",
    "Centro Familiar Vida Nueva Londres": "https://register-of-charities.charitycommission.gov.uk/charity-search/-/charity-details/5128503/contact-information",
    "Ceylon 1 Limited": "https://www.ifs.com/about/careers-at-ifs",
    "Chamber Orchestra of Europe": "https://www.coeurope.org/coe-vacancies/",
    "Charles Stanley & Co. Limited": "https://www.charles-stanley.co.uk/about-us/careers",
    "Charminar Restaurant Ltd": "https://ca.indeed.com/cmp/Charminar-Indian-Cuisine",
    "Charter School Capital UN, Ltd": "https://growschools.com/careers/",
    "Cheek by Jowl Theatre Company Limited": "https://www.cheekbyjowl.com/about/working-with-us/",
    "Cheq Technologies (UK) Limited": "https://cheq.ai/careers/",
    "Cherubim and Seraphim Holy Temple Church of Christ": "https://register-of-charities.charitycommission.gov.uk/charity-search/-/charity-details/1001787/contact-information",
    "Chesamel Group Limited": "https://chesamel.com/chesamel-jobs/",
    "Chesters (Tooting) Ltd": "https://uk.indeed.com/q-chester-l-tooting-jobs.html",
    "Cheung Kong Graduate School of Business (Europe) Limited": "https://english.ckgsb.edu.cn/worldwide/about/careers/",
    "Chick Chicken Plumstead Limited": "https://uk.indeed.com/q-chicken-l-plumstead-jobs.html",
    "Children Assisted in a Real Environment Ltd": "https://www.cv-library.co.uk/list-jobs/381379/Children-Assisted-in-a-Real-Environment-Ltd",
    "China Eastern Airlines Corporation Limited": "https://job.ceair.com/global/index.html",
    "China Garden Yang Ltd": "https://uk.indeed.com/cmp/China-Garden",
    "China Tang London Limited": "https://www.chinatanglondon.co.uk/careers",
    "China Unicom (Europe) Operations Limited": "https://www.chinaunicomglobal.com/eu/join-us.php",
    "Chinese Medicine Centre (London) Ltd": "https://uk.indeed.com/q-chinese-medical-l-london-jobs.html",
    "Choice Textile Limited": "https://uk.indeed.com/cmp/Choice-Textile-Ltd",
    "Chouchou Europe Ltd": "https://uk.indeed.com/cmp/Chouchou-8",
    "Chris Homecare Limited": "https://uk.indeed.com/q-chris-care-jobs.html",
    "Christian Spiritual Warfare Ministry": "https://careers.samaritanspurse.org/",
    "Ci&T UK Limited": "https://ciandt.com/uk/en-gb/careers",
    "Citadel Commerce UK Limited": "https://www.citadel.com/careers/open-opportunities/",
    "Citadel Enterprise Europe Limited": "https://www.citadel.com/careers/",
    "Citadel Events Limited": "https://www.citadel.com/careers/",
    "City Executive Consultants Limited": "https://cityexec.com/",
    "City Link Property Management Ltd": "https://www.cv-library.co.uk/list-jobs/451710/City-Link-Property-Management",
    "City Mandarin Limited": "https://uk.indeed.com/q-city-mandarin-jobs.html",
    "City Offices Real Estate Limited": "https://careers.cityoflondon.gov.uk/",
    "City Realtor Ltd": "https://cityrealtor.co.uk/now-recruiting/",
    "City of London Corporation": "https://careers.cityoflondon.gov.uk/",
    "Clarabridge UK Ltd": "https://uk.indeed.com/cmp/Clarabridge",
    "Cleantech Group Europe Limited": "https://www.cleantech.com/careers/",
    "Clear Score Technology Limited": "https://www.clearscore.com/careers",
    "Clearview Healthcare Partners (UK) Limited": "https://clearviewhcp.com/careers/",
    "Clement Mind Limited": "https://www.clements.com/careers/",
    "Cleo AI Ltd": "https://web.meetcleo.com/careers",
    "Cleveland & Co Associates Limited": "https://cleveland-co.com/life/our-jobs/",
    "Clivedale Ventures Limited": "https://www.clivedale.com/",
    "Clothing Care London Ltd": "https://uk.indeed.com/m/jobs?q=Clothing+Care&l=London",
    "Cloud Capital LLP": "https://cldcap.com/",
    "Cloud Lending UK Ltd": "https://uk.indeed.com/q-cloud-lending-l-london-jobs.html",
    "Co London United Ltd": "https://uk.indeed.com/cmp/London-United",
    "Cobrest Limited T/A H Lloyds Chemist": "https://lpclinicalhomecare.co.uk/careers/",
    "Coda Restaurants Ltd T/A The Ninth": "https://www.theninthlondon.com/",
    "Codegen Ltd": "https://codegen.co.uk/we-are-hiring/",
    "Coffee Dock (LN) Ltd": "https://uk.indeed.com/cmp/Coffee-Dock-(ln)-Ltd/salaries?job_category=retail&location=GB%2FENG",
    "Cognia Cloud Limited t/a Smarsh": "https://www.smarsh.com/careers/",
    "Cognita Schools Limited": "https://www.cognita.com/our-careers/",
    "Cogora Group Ltd": "https://www.cogora.com/careers/",
    "Colliers International Property Consultants Limited": "https://www.colliers.com/en-gb/careers",
    "Colt Technology Services Group Limited": "https://www.colt.net/careers/",
    "Com-Centre (UK) Ltd": "https://www.computacenter.com/en-gb/careers",
    "Come On London Ltd": "https://careers.cityoflondon.gov.uk/",
    "Communications International Group": "https://www.ask4ci.com/careers/",
    "Communications Software (Airline systems) Limited": "https://www.oases.aero/careers/",
    "Community Church of God": "https://oscar.org.uk/opportunities/viewall",
    "Community Housing and Therapy": "https://www.communityhousing.co.uk/careers/working.php",
    "CompatibL Technologies Ltd": "https://www.compatibl.com/careers/",
    "Complement Therapeutics Limited": "https://complementtx.com/job-openings/",
    "Complete Pilates Medical Ltd": "https://complete-pilates.co.uk/join-our-team/",
    "Concrete Testing Solutions Limited": "https://uk.indeed.com/q-concrete-testing-solutions-jobs.html",
    "Configure One Europe Ltd": "https://www.glassdoor.co.uk/Overview/Working-at-Configure-One-EI_IE1071364.11,24.htm",
    "Congregation of Our Lady, Canonesses of St Augustine CIO": "https://register-of-charities.charitycommission.gov.uk/cy/charity-search?p_p_id=uk_gov_ccew_onereg_charitydetails_web_portlet_CharityDetailsPortlet&p_p_lifecycle=2&p_p_state=maximized&p_p_mode=view&p_p_resource_id=%2Faccounts-resource&p_p_cacheability=cacheLevelPage&_uk_gov_ccew_onereg_charitydetails_web_portlet_CharityDetailsPortlet_objectiveId=A11799793&_uk_gov_ccew_onereg_charitydetails_web_portlet_CharityDetailsPortlet_priv_r_p_mvcRenderCommandName=%2Faccounts-and-annual-returns&_uk_gov_ccew_onereg_charitydetails_web_portlet_CharityDetailsPortlet_priv_r_p_organisationNumber=5078019",
    "Congregation of the Mission (The Vincentian Fathers)": "https://www.vincentian.org/",
    "Connect 4 Energy Limited": "http://www.connect4recruitment.com/",
    "Connect Managed Services (UK) Ltd": "https://www.weconnect.tech/about-us/careers/",
    "Connected Places Catapult": "https://cp.catapult.org.uk/careers/",
    "Consilio Global (UK) Limited": "https://uk.consilio.com/about-consilio/careers/",
    "Consilium": "https://www.consilium.europa.eu/en/general-secretariat/jobs/vacancies/",
    "Construction Surge Ltd": "https://uk.indeed.com/cmp/Surge-Building-Services-Ltd",
    "Consult Plex Limited": "https://www.plex.tv/en-gb/careers/",
    "Consulting W8 Ltd": "https://uk.indeed.com/q-consultant-l-london-w8-jobs.html",
    "Content Calendr Limited": "https://uk.indeed.com/q-content-calendar-jobs.html",
    "Contracta Construction UK Limited": "http://www.contractaconstruction.co.uk/",
    "Convene UK Holdings Limited": "https://convene.com/careers/",
    "Convenience Stop": "https://www.onestop.co.uk/careers/",
    "Cool Company Management Ltd": "https://www.coolcoltd.com/",
    "Core Laboratories (U.K.) Limited": "https://www.corelab.com/careers/",
    "CoreStream Ltd": "https://www.corestream.co.uk/category/careers/",
    "Coriander (Vauxhall) Ltd": "https://www.vauxhall.co.uk/unpublished-pages/about/careers/vauxhall-careers/roles.html",
    "Corona Packaging Ltd": "https://www.indeed.com/m/jobs?q=Corona+Packaging",
    "Corporate Research Forum Limited": "https://www.crforum.co.uk/",
    "Corten Ltd": "https://www.cv-library.co.uk/list-jobs/363515/Corten-Ltd",
    "Cortland Development UK Limited": "https://cortland.co.uk/careers/",
    "Council for World Mission (UK)": "https://www.cwmission.org/job-opportunities-ms-2/",
    "County Accountants Limited": "https://www.accountancycareers.co.uk/",
    "Course5 Intelligence Limited": "https://www.c5i.ai/careers/",
    "Courtney Smith Solicitors LLP": "https://solicitors.lawsociety.org.uk/office/614601/courtney-smith-solicitors-llp",
    "Coverys Managing Agency Limited": "https://www.coverys.com/careers",
    "Cox Workshops Limited": "https://coxlondon.com/careers/",
    "Cozy Tree Daycare Ltd": "https://www.cozytree.co.uk/",
    "Crane Venture Partners LLP": "https://careers.crane.vc/jobs",
    "Create Cap Studios Ltd": "https://createstudios.org.uk/opportunities/",
    "Creative Independent Living": "https://uk.indeed.com/cmp/Creative-Independent-Living-Limited",
    "Cresta World Travel Limited": "https://www.crestaworldtravel.co.uk/",
    "Crestbridge Uk Limited": "https://www.crestfos.com/careers/",
    "Cresthall Ventures Limited": "https://shootsandleaves.uk/privacy-notice/",
    "Crownwise Ltd": "https://uk.indeed.com/cmp/Crownwise-Ltd",
    "Croydon Kokoro Limited": "https://kokorouk.com/careers/vacancies/",
    "Crystal Facilities Management Limited": "https://crystalservices.uk.com/career/",
    "Crystal London (Green Street) Ltd": "https://uk.indeed.com/q-crystal-london-l-enfield-jobs.html",
    "Crystal Management Services Ltd": "https://crystalservices.uk.com/career/",
    "Crystal Patisserie Limited": "https://www.crystalpatisserie.co.uk/",
    "Cubitt House Group": "https://www.cubitthouse.co.uk/careers/",
    "Cult London Limited": "https://cultldn.com/our-people/",
    "Currie & Brown International Limited": "https://www.curriebrown.com/en/careers/opportunities/",
    "Curry Land Limited": "https://uk.indeed.com/cmp/Curry-Land-Ltd?campaignid=mobvjcmp&from=mobviewjob&tk=1i1rfc9dqk7t580h&fromjk=c37cdc632987ec17",
    "Curry Nights Limited": "https://uk.indeed.com/q-curry-nights-ltd-l-london-jobs.html",
    "Curzon Square Limited": "https://www.curzon.com/careers/",
    "Cutfield Freeman & Company Limited": "https://www.cfandco.com/en/",
    "Cyprus bakery ltd": "https://uk.indeed.com/q-bakery-l-cyprus-station-jobs.html",
    "D S Property Finance Ltd": "https://uk.indeed.com/cmp/Ds-Property-Finance-Ltd",
    "D SENSE THERAPY LTD": "https://www.sense.org.uk/get-involved/jobs-at-sense/",
    "D& D Restaurant LTD": "https://www.danddlondon.com/careers/",
    "D. I . Design & Development Consultants (UK) Limited": "https://www.dezeenjobs.com/",
    "D1 TRAVEL LTD": "https://uk.indeed.com/q-d1-l-london-jobs.html",
    "D2L Europe Limited": "https://www.d2l.com/careers/jobs/",
    "DA BUREAU LIMITED": "https://uk.indeed.com/q-de-bureau-jobs.html",
    "DAC GROUP UK OPERATIONS LTD.": "https://www.dacgroup.com/en-gb/careers/",
    "DALSTON MINI CABS LTD": "https://uk.indeed.com/Taxi-jobs-in-East-London",
    "DANNY SULLIVAN & SONS LTD": "https://www.dannysullivan.co.uk/job-board/",
    "DAY-MER TURKISH & KURDISH COMMUNITY CENTRE": "https://daymer.org/vacancies/",
    "DBFS Limited": "https://www.dbfs.co.uk/careers/",
    "DC Initiatives LLP": "https://www.dcadvisory.com/join-us/",
    "DCC Holdings (UK) Limited": "https://www.dcc.ie/careers",
    "DDDDDD LIMITED": "https://www.cv-library.co.uk/list-jobs/251907/DDD-Ltd",
    "DE BEERS UK LIMITED": "https://www.debeersgroup.com/careers/current-vacancies",
    "DEL Interiors (UK) Limited": "https://www.dezeenjobs.com/",
    "DELIGHT COFFEE LTD": "https://uk.indeed.com/q-cafe-delight-jobs.html",
    "DELUXSMILE LIMITED": "https://www.deluxe-recruitment.co.uk/",
    "DGGR Limited": "https://careers.domesticandgeneral.com/",
    "DIAMOND FUNCTIONS LIMITED": "https://www.diamond.ac.uk/Careers/Vacancies.html",
    "DIAMOND HEAD SERVICES LTD": "https://ca.indeed.com/cmp/Diamond-Head-Consulting",
    "DIANA LONDON LTD": "https://www.diana.nato.int/join-our-team.html",
    "DILPASAND COMMERCIAL ROAD ONE LTD": "https://uk.indeed.com/cmp/Dilpasand-Commercial-Road-One-Ltd",
    "DIVA HAIR & COSMETICS LTD": "https://uk.indeed.com/cmp/Diva-Hair-and-Beauty",
    "DJP Healthcare Limited": "https://uk.indeed.com/q-d-j-p-jobs.html",
    "DOCKS INN LTD": "https://uk.indeed.com/m/jobs?q=Docks&l=Southampton",
    "DONGYI MEDICAL DEVICE TECHNOLOGY CO., LTD": "https://uk.indeed.com/cmp/Dongyi-Sourcing-UK-Limited?campaignid=mobvjcmp&from=mobviewjob&tk=1i3pc9059kibo80i&fromjk=d98ca7f90e2cb538",
    "DORSEY & WHITNEY (EUROPE) LLP": "https://www.dorsey.com/careers",
    "DOWNUNDER GEOSOLUTIONS (LONDON) PTY LIMITED": "https://dug.com/careers-at-dug/",
    "DR JOHNSON DEVELOPMENTS LTD": "https://www.glassdoor.co.uk/job-listing/graphic-designer-android-developer-dr-johnson-developments-ltd-JV_IC2671300_KO0,34_KE35,62.htm?jl=1009368641127",
    "DR LONDON CONSTRUCTION LTD": "https://www.nlcltd.uk/",
    "DRAGAN K LTD": "https://www.cv-library.co.uk/list-jobs/288721/Dragon-Recruitment-Ltd",
    "DREAM HOUSE BUILD LTD": "https://dhclondon.co.uk/",
    "DREAMS UNLIMITED EVENTS LTD": "https://dream.ca/careers/",
    "DSK Partners LLP": "https://dskllp.com/about-us/careers/",
    "DT & T Corporation Limited": "https://dttcl.com/careers/",
    "DT Global International Development UK Ltd": "https://dt-global.com/work-with-us/",
    "DTCC Europe Limited": "https://www.dtcc.com/careers",
    "DTN Europe UK Limited": "https://www.dtn.com/about-us/careers/",
    "DY UK TRANSPORT LTD": "https://careers.dft.gov.uk/",
    "DYNAMIC HEAD LTD": "https://www.elcompanies.co.uk/en-gb/careers",
    "DYNAMIC INVESTMENTS (LONDON) LTD": "https://www.simplyhired.co.uk/search?q=dynamic+investments+london+ltd&l=london",
    "DYNATA GLOBAL UK LTD": "https://careers.dynata.com/",
    "Daily Fresh Food 2 Limited": "https://uk.indeed.com/m/jobs?q=Daily+Fresh",
    "Daiwa International Capital Partners Limited": "https://www.daiwa-icp.com/",
    "Dalia Holdings Limited": "https://daliajobs.com/",
    "Dalston Hospitality Ltd": "https://uk.indeed.com/q-hospitality-l-dalston-jobs.html",
    "Danimi Operations UK Limited": "https://careers.homeoffice.gov.uk/",
    "Dartford Pizza Ltd": "https://uk.indeed.com/Pizza-jobs-in-Dartford",
    "Dashkart Limited": "https://uk.indeed.com/cmp/Dashkart-Ltd",
    "Data Trek Technologies Ltd": "https://www.trekbikes.com/gb/en_GB/careers/",
    "De Bohun Care Ltd": "https://uk.indeed.com/cmp/De-Bohun-Care-Ltd-1",
    "De Vere Care Partnership LTD": "https://www.dvcgroup.co.uk/careers-at-de-vere-care9a62ff17",
    "Decision Technology limited": "https://decision.tech/careers/",
    "Delegat Europe Limited": "https://www.delegat.com/wine-career-opportunities",
    "Delirium Limited T/A The Winery": "https://www.thewineryuk.com/staff/",
    "Delmon Pizza Limited": "https://uk.indeed.com/cmp/Delmon-Pizza-Ltd",
    "Delta Consulting Group Ltd": "https://delta-cgi.com/careers/",
    "Deluxe Services Limited": "https://www.deluxe-recruitment.co.uk/",
    "Denali Advanced Integration Europe Limited": "https://www.denaliai.com/careers/",
    "Dental Harmony LTD": "https://www.dentalharmony.co.uk/",
    "Department for Transport": "https://careers.dft.gov.uk/",
    "Deptford Super Market": "https://uk.indeed.com/q-supermarket-l-deptford-jobs.html",
    "Derayo Ltd": "https://www.diageo.com/en/careers",
    "Derma Clinic Limited": "https://uk.indeed.com/q-dermal-clinic-jobs.html",
    "Designhouse Consultants Ltd": "https://designhouse.co.uk/",
    "Desmond Motors LTD": "https://www.desmondmotors.co.uk/careers",
    "Destiny house": "https://www.indeed.com/m/jobs?q=Destiny%27s+House",
    "Dezeen Limited": "https://www.dezeenjobs.com/",
    "Dhaba Express Limited": "https://ca.indeed.com/cmp/Dhaba-Express",
    "Di Saporito Ltd": "https://www.diageo.com/en/careers",
    "Diahearts Limited": "https://www.diageo.com/en/careers",
    "DibCo Limited": "https://ca.indeed.com/cmp/Dibco-Underground-Ltd",
    "Diffusion PR and Communications Limited": "https://diffusionpr.com/careers/",
    "Digital Catapult": "https://www.digicatapult.org.uk/apply/careers/current-vacancies/",
    "Digital Completion UK Limited": "https://solicitors.lawsociety.org.uk/office/33648/digital-completion-uk-limited-t-a-pexa-",
    "Digital Insight Technologies Limited trading as Xapien": "https://xapien.com/careers",
    "Digital Mobile Innovations Limited": "https://dminc.com/careers/open-positions/",
    "Digital Moneybox Limited": "https://www.moneyboxapp.com/careers",
    "Digital Taxonomy Limited": "https://uk.indeed.com/m/jobs?q=Digital+Taxonomy",
    "Digital Therapeutics Ltd": "https://uk.indeed.com/q-digital-therapeutics-l-london-jobs.html",
    "Din & Din Limited T/A Subway": "https://www.subway.com/en-GB/careers",
    "Direct Link Technologies Ltd": "https://directlink.ai/careers",
    "Direct To Customers Limited": "https://uk.indeed.com/q-direct-to-customers-limited-l-london-jobs.html",
    "Dirty Laundry": "https://uk.indeed.com/cmp/Dirty-Laundry-1?campaignid=mobvjcmp&from=mobviewjob&tk=1i3n2djf82f3q007&fromjk=15c69dc020a0a116",
    "Discovery Communications Europe Limited": "https://uk.indeed.com/q-discovery-communications-europe-l-london-w1a-jobs.html",
    "Disys U.K Limited": "https://careers.disys.com/jobs/contract",
    "Ditty's Castledawson Ltd": "https://uk.indeed.com/cmp/Ditty's-Bakery/locations/NIR/Castledawson",
    "Document Risk Solutions Ltd": "https://drs-als.com/careers/",
    "Doddle Parcel Services Ltd": "https://www.doddle.com/",
    "Dog & Groom LTD": "https://uk.indeed.com/q-dog-&-groom-l-london-jobs.html",
    "Dogma Group Ltd": "https://dogmagroup.co.uk/career/",
    "Doherty IT Solutions Ltd Trading As Doherty Associates": "https://www.doherty.co.uk/careers/",
    "Dolce Leisure Group": "https://www.dolce.co.uk/careers/working-with-dolce/",
    "Double Ark Ltd": "https://www.doubleark.co.uk/job-advert",
    "Double Negative Limited": "https://www.dneg.com/careers/",
    "Doubletree by Hilton London Elstree": "https://uk.indeed.com/q-doubletree-by-hilton-l-elstree-jobs.html",
    "Dover Street Logistics Limited": "https://www.dstreetlogistics.co.uk/",
    "Downe Catering Ltd": "https://uk.indeed.com/cmp/Mustard-(downe-Catering-Limited)",
    "Dr Curran and Partners": "https://www.claphamhealth.nhs.uk/",
    "Drink the Drip Ltd": "https://www.wsp.com/en-gb/careers",
    "Droit Public Limited Company": "https://droit.tech/careers/",
    "Drop Fix Limited": "https://www.1-fix.com/careers",
    "Dublin Meats Limited": "https://ie.indeed.com/q-dublin-meat-company-l-artane,-county-dublin-jobs.html",
    "Duck Creek Technologies Limited": "https://www.duckcreek.com/careers/",
    "Duco Technology Limited": "https://du.co/careers/",
    "Duke of wellington": "https://www.thedukeofwellingtonhalifax.co.uk/jobs",
    "Dulwich Dental Clinic Ltd": "https://uk.indeed.com/cmp/Dulwich-Dental-Clinic?campaignid=mobvjcmp&from=mobviewjob&tk=1h6e2nbpjk7fq800&fromjk=80ada951f68aa4f3",
    "Dulwich Spice Ltd": "https://uk.indeed.com/q-spices-l-london-jobs.html",
    "Dynamic Care Support Ltd": "https://uk.indeed.com/cmp/Dynamic-Care-Support-Ltd",
    "Dynamic Food Services Ltd": "https://uk.indeed.com/q-dynamic-food-company-l-uxbridge-jobs.html",
    "E ONE MOT Centre  Limited": "https://www.eon.com/en/about-us/careers.html",
    "E&B MEAT PRODUCTS LTD": "https://www.indeed.com/cmp/E&B-Meat-Product-Ltd",
    "E&I Engineering Ltd": "https://www.vertiv.com/en-emea/about/careers/engineering-jobs/",
    "E.M.R.  Search & Selection Limited": "https://www.emrrecruitment.co.uk/",
    "E12 Kebabish Limited": "https://uk.indeed.com/cmp/E12-Kebabish",
    "E16 CONSTRUCTION LIMITED": "https://uk.indeed.com/m/jobs?q=Construction+Jobs&l=London+E16",
    "E17 NURSERY LIMITED": "https://uk.indeed.com/cmp/E17-Nursery-Limited",
    "EAK Management, UK Ltd": "https://eakdigital.com/careers/",
    "EAM London Limited": "https://eam.co.uk/vacancies/",
    "EAST JAPAN RAILWAY COMPANY": "https://www.jreast.co.jp/recruit/new-graduate/english/general.html",
    "EAST RIVER DEVELOPMENT LTD": "https://www.indeed.com/cmp/East-River-Development-Allliance",
    "ECI Ventures Ltd": "https://www.ecipartners.com/",
    "ECLIPSE PHARMA LTD": "https://uk.indeed.com/cmp/Eclipse-Pharmacy",
    "ECO HOMEZ LIMITED": "https://uk.indeed.com/m/jobs?q=Eco+Homes+Company",
    "ECONO PIZZA AND PERI PERI LTD": "https://econopizza-periperi.co.uk/",
    "ECS SERVICES LTD": "https://www.ecslimited.com/careers/",
    "EDGBASTON INVESTMENT PARTNERS LLP": "https://edgbastonip.com/",
    "EDGE architecture + design Limited": "https://edgedesignworkshop.com/careers/",
    "EDMONTON COFFEE LTD": "https://uk.indeed.com/q-coffee-l-edmonton-jobs.html",
    "EDUCATION OFFICE  EMBASSY OF GREECE": "https://www.mfa.gr/en/career-opportunities/",
    "EFES FULHAM LIMITED": "https://uk.indeed.com/cmp/Efes-Turkish-Restaurant",
    "EGS Services Limited": "https://www.egs.org.uk/careers/",
    "EJ Interiors Ltd": "https://www.cv-library.co.uk/list-jobs/354800/EJ-Interiors",
    "ELEKS Software UK Limited": "https://careers.eleks.com/",
    "ELITE SPORTS MANAGEMENT LTD": "https://uk.indeed.com/q-elite-sports-agency-jobs.html",
    "EM SCIENTIFIC LIMITED": "https://uk.indeed.com/m/jobs?q=Em+Scientific",
    "EMBASSY OF SPAIN": "https://www.exteriores.gob.es/Embajadas/abuja/en/Embajada/Paginas/Ofertas-de-empleo.aspx",
    "EMC-Energy Market Consultants (UK) Ltd": "https://www.fgenergy.com/company/contact/fge-london.aspx",
    "EMERGENCY-LIFE SUPPORT FOR CIVILIAN VICTIMS OF WAR AND POVERTY, UK": "https://emergencyuk.org/work-with-us/in-the-field/",
    "EMINENT SERVICES LIMITED": "https://uk.indeed.com/q-eminent-recruitment-jobs.html",
    "EMMY CONSTRUCTION LTD": "https://uk.indeed.com/cmp/Emmy-Construction-Ltd",
    "EMPOWERING THERAPY LTD": "https://uk.indeed.com/q-empower-therapies-jobs.html",
    "EN+ Group IPJSC (London Branch)": "https://www.enplusgroup.com/en/sustainability/people/",
    "ENA London UK Limited": "https://www.energynetworks.org/about/careers",
    "ENDEAVOUR RETAIL LTD T/A ANGEL FOOD and WINE": "https://endeavourgroupcareers.com.au/",
    "ENERGY BLOOM MARKETING LTD": "https://www.bloomenergy.com/careers/",
    "ENVY POST PRODUCTION LIMITED": "https://www.envypost.co.uk/careers/",
    "EQUUS SOFTWARE UK LIMITED": "https://www.equusoft.com/company/careers/",
    "ES Global Ltd": "https://es.global/careers/",
    "ESPH Healthcare Ltd": "https://uk.indeed.com/cmp/Esph",
    "ESQUIRES COFFEE SHEPHERD'S BUSH LIMITED": "https://esquirescoffee.co.uk/news/meet-our-team-barista/",
    "ESV International Ltd": "https://ph.indeed.com/cmp/Esv-International-Corp",
    "ETC Management Ltd": "https://www.etcvenues.com/careers/",
    "EURONET 360 FINANCE LIMITED": "https://www.euronetworldwide.com/about-euronet/careers/",
    "EUROPEAN COUNSEL LTD": "https://www.consilium.europa.eu/en/general-secretariat/jobs/",
    "EVA AIRWAYS CORPORATION - UK BRANCH": "https://www.evaair.com/en-gb/about-eva-air/careers/",
    "EVOLVE ARCHITECTURE LIMITED": "https://evolveea.com/careers/",
    "EWI STORE LTD": "https://ewistore.co.uk/careers/",
    "EXPRESS DRY CLEANERS LTD": "https://uk.indeed.com/cmp/Express-Dry-Cleaners",
    "Ealing Hair and Beauty Limited": "https://uk.indeed.com/m/jobs?q=Hair+Beauty&l=Ealing",
    "Ealing Trailfinders Professional Rugby Management Limited": "https://ealingtrailfinders.com/ealing-trailfinders-rugby-club/",
    "Earls court food limited": "https://uk.indeed.com/l-earls-court-jobs.html",
    "Earlybird Venture Capital UK LTD": "https://jobs.earlybird.com/",
    "Earnest (London) Ltd": "https://earnest-agency.com/b2b-agency/join-earnest/",
    "East London Community College Ltd": "https://uk.indeed.com/East-London-Community-College-jobs",
    "East London Pizza Ltd": "https://uk.indeed.com/q-pizza-l-east-london-jobs.html",
    "East Shack Ltd": "https://uk.indeed.com/q-shack-jobs.html",
    "Easy Claim Limited": "https://www.cv-library.co.uk/list-jobs/414910/Easy-Claim-Ltd",
    "Eat Zone Limited": "https://uk.indeed.com/q-eat-zone-l-london-jobs.html",
    "Ebury Partners UK Ltd": "https://careers.ebury.com/",
    "Eco Sports Limited": "https://www.greenjobs.co.uk/",
    "Ecole Jeannine Manuel UK": "https://www.ecolejeanninemanuel.org.uk/",
    "Economic and Commercial Office - Spanish Embassy": "https://www.exteriores.gob.es/Embajadas/londres/en/Paginas/index.aspx",
    "Eden Fine Art London Limited": "https://www.cv-library.co.uk/list-jobs/405633/Eden-Fine-Art",
    "Edge Health": "https://www.edgehealth.co.uk/careers/",
    "Education Endowment Foundation": "https://educationendowmentfoundation.org.uk/about-us/careers-at-eef/life-at-the-eef/join-our-team",
    "Edukators London Ltd": "https://alison.com/course-creators/edukators-london-ltd",
    "Efes Barking Limited": "https://uk.indeed.com/cmp/Efes-Turkish-Restaurant",
    "Eight Roads Services (UK) Limited": "https://jobs.eightroads.com/companies",
    "Eldon Construction Limited": "https://uk.indeed.com/cmp/Eldon-Tool-and-Engineering-Ltd",
    "Electoral Commission": "https://www.electoralcommission.org.uk/about-us/working-us",
    "Electro Gas Plus Limited": "https://www.electrogas.com.mt/contact-us-2/",
    "Elements Digital Ltd": "https://www.element.com/careers",
    "Elephant Healthcare Limited": "https://elephant.healthcare/careers/",
    "Elexon Limited": "https://www.elexon.co.uk/about/about-elexon/working-at-elexon/",
    "Elite Detailing and Protection": "https://uk.indeed.com/cmp/Elite-Detailing-and-Protection",
    "Elliott Harper Productions Limited": "https://elliottandharper.com/",
    "Elmwoods Group UK Limited": "https://www.elmwoods.co.uk/careers",
    "Eltham College": "https://www.eltham-college.org.uk/about-us/work-with-us/",
    "Embassy of Brazil in London": "https://www.gov.br/mre/pt-br/embaixada-londres",
    "Embassy of Japan": "https://www.uk.emb-japan.go.jp/itprtop_en/index.html",
    "Embassy of the Kingdom of Bahrain": "https://www.mofa.gov.bh/en/career",
    "Embassy of the Kingdom of the Netherlands": "https://www.netherlandsandyou.nl/web/united-kingdom/vacancies",
    "Emerald Telecom Limited": "https://www.cv-library.co.uk/list-jobs/296749/Emerald-Telecom-Ltd",
    "Encompass Digital Media Services Limited": "https://www.encompass.tv/careers/",
    "Enji Technologies": "https://enjin.io/opportunities",
    "Enlight Group Limited": "https://enlightenergy.co.il/data/career-at-enlight/",
    "Enlighten Software Limited": "https://enlighten-opex.com/about-us/careers/",
    "Enternships Limited": "https://careers.ihg.com/en/",
    "Enterprise Singapore": "https://www.enterprisesg.gov.sg/about-us/careers",
    "Entertainment One UK Limited": "https://uk.indeed.com/cmp/Entertainment-One",
    "Entrepreneur First Operations Limited": "https://www.joinef.com/about/careers/",
    "Environ Audio Ltd": "https://myenviron.co.uk/careers/",
    "Environmental Power International (UK) Limited": "https://uk.indeed.com/m/jobs?q=Environmental+Power+International+%28UK%29",
    "Envoy EMEA Limited": "https://www.envoyglobal.com/careers/",
    "Epicure Number 2 Ltd": "https://uk.indeed.com/cmp/Epicure-Number-2-Ltd",
    "Epsilon Telecommunications Ltd": "https://epsilontel.com/careers/",
    "Equiti Capital UK Limited": "https://www.equiti.com/career/",
    "Eric Parry Architects Ltd": "https://www.ericparryarchitects.co.uk/careers/",
    "Escape Beauty & Events Ltd": "https://uk.indeed.com/q-beauty-escape-jobs.html",
    "Estee Lauder Cosmetics Limited": "https://www.elcompanies.co.uk/en-gb/careers",
    "Esubstance T/A Ink": "https://ink-global.com/company-details/",
    "Ethixbase UK Limited": "https://ethixbase360.com/company/ethixbase360-careers-2/",
    "Euroeyes London Knightsbridge Limited": "https://euroeyes.com/euroeyes-opening-of-flagship-eye-clinic-in-london/",
    "Eurofin International Ltd": "https://careers.eurofins.com/uk/",
    "Evans Associates UK Limited": "https://www.mevans.co.uk/vacancies/",
    "Evelyn Partners Group Limited": "https://www.evelyn.com/careers/",
    "Evercore Group Services Limited": "https://www.evercore.com/careers/the-evercore-difference/",
    "Evercore ISI International Limited": "https://www.evercore.com/careers/the-evercore-difference/",
    "Everest Advisors (UK) Ltd": "https://www.everestglobal.com/gb-en/career-opportunities/overview",
    "Evergreen Surgery Limited": "https://evergreensurgery.nhs.uk/",
    "Evo Capital Management Europe Ltd": "https://www.evo-group.co.uk/join-us/",
    "Exafield LTD": "https://uk.indeed.com/cmp/Exafield-Ltd",
    "Exana Limited": "https://careers.next.co.uk/",
    "Excel LEC Limited": "https://www.cv-library.co.uk/list-jobs/412862/EXCEL-LEC-Limited",
    "Excel Plumbing and Heating Supplies Ltd": "https://excelplumbingandheating.co.uk/",
    "Exel Foods Ltd": "https://uk.indeed.com/q-excel-foods-jobs.html",
    "Expedition Growth Capital Ltd": "https://expedition.capital/",
    "Express S Solution Ltd": "https://uk.indeed.com/q-express-solutions-group-jobs.html",
    "Express by Holiday Inn": "https://careers.ihg.com/en/our-brands/holiday-inn-express/",
    "Extra Cash & Carry LTD": "https://uk.indeed.com/q-extra-cash-carry-l-london-n17-jobs.html",
    "Eyes at Home Limited": "https://www.visionexpresscareers.com/",
    "F/CE. LONDON LAB LTD": "https://www.diageo.com/en/careers",
    "FACEPHI BEYOND BIOMETRICS LTD": "https://en.facephi.com/",
    "FAIR.XYZ LIMITED": "https://fair.xyz/",
    "FAIRFIELD CAPITAL LIMITED": "https://uk.indeed.com/cmp/Cd-Fairfield-Capital",
    "FALAFEL FOOD CO LTD": "https://uk.indeed.com/cmp/Falafel-Restaurant",
    "FAMILY BAKERY LTD": "https://uk.indeed.com/m/jobs?q=Family+Bakery",
    "FASHION DESIGNORS LIMITED": "https://uk.fashionjobs.com/",
    "FB&C Ltd": "https://www.fbcmb.co.uk/careers/our-latest-vacancies/",
    "FEEL&GOOD LTD": "https://uk.indeed.com/cmp/The-Feel-Good-Group-Ltd",
    "FELTHAM HALAL MEAT (UK) LTD": "https://uk.indeed.com/q-halal-l-england-jobs.html",
    "FF Clarion Limited": "https://www.clarionhg.com/careers",
    "FF Management Limited": "https://www.indeed.com/cmp/Ff-Management",
    "FID TRUST INTERNATIONAL LTD": "https://www.fiduciarytrust.com/careers",
    "FIL TRADING LTD T/As BIKENEARME": "https://uk.indeed.com/cmp/Fil-Trading-Ltd",
    "FINE CUISINES LONDON LIMITED": "https://uk.indeed.com/q-london-fine-dining-jobs.html",
    "FINTECHOS TECHNOLOGY UK LTD": "https://fintechos.com/careers/",
    "FISH FACE LONDON LIMITED": "https://uk.indeed.com/q-fish-face-jobs.html",
    "FIT SHIRTS LTD": "https://www.cv-library.co.uk/list-jobs/330676/FIT-Shirts-Ltd",
    "FIX&BUILD HOMES LTD": "https://bloorhomes.com/careers",
    "FLAVOURS FOOD AND CATERING LIMITED": "https://uk.indeed.com/q-flavours-foods-l-barnsley-jobs.html",
    "FM London LTD": "https://fmrecruitment.co.uk/",
    "FOOD ELEMENTS LIMITED": "https://www.element.com/careers",
    "FOOD EXTRAORDINAIRE LIMITED": "https://uk.indeed.com/cmp/Food-Extraordinaire-Ltd",
    "FOOD LINK (LONDON) LIMITED": "https://uk.indeed.com/q-food-link-jobs.html?start=20",
    "FORESCOUT TECHNOLOGIES UK LTD": "https://www.forescout.com/company/careers/",
    "Faculty Opinions Limited": "https://connect.h1.co/",
    "Faculty Science Limited": "https://faculty.ai/join-the-team/",
    "Faire Wholesale UK Ltd.": "https://www.faire.com/en-gb/careers",
    "Fairhill Lawyers Ltd": "https://www.simplyhired.co.uk/job/DL5m9xumqK73qvXriJY1ELEyFM9XrmtOJAtnH24zuQ_r08TTIj1ZLA",
    "Fairmont Hotels and Resorts": "https://careers.accor.com/global/en/jobs",
    "Faisen Ltd": "https://uk.fashionjobs.com/",
    "Far East Holdings Ltd T/A KOYN": "https://www.fareast.com/en/about-us/careers",
    "Farm Lane Landscaping": "https://www.farmlanelandscaping.co.uk/",
    "Fashion Cliff Limited": "https://uk.indeed.com/q-fashion-l-mudeford-and-friars-cliff-jobs.html",
    "Fasken Martineau LLP": "https://www.fasken.com/en/careers",
    "Fast Computers & Mobile Services Ltd": "https://uk.indeed.com/Fast-Computer-&-Mobile-Services-Ltd-jobs",
    "Fast Property Management Limited": "https://uk.indeed.com/q-fast-property-management-jobs.html",
    "Fearnleys Shipbrokers UK Ltd": "https://fearnleys.com/careers/",
    "Feelunique International Limited": "https://www.feelunique.com/careers",
    "Fill Function UK Ltd": "https://uk.indeed.com/q-fill-function-uk-l-birmingham-jobs.html",
    "Find Digs Limited": "https://www.finddigs.co.uk/",
    "Fineway Cash & carry Ltd": "https://uk.indeed.com/cmp/Fineway-Cash-and-Carry",
    "Fios Food Centre": "https://uk.indeed.com/cmp/Fio's-Food-Center",
    "Fireproof Studios Limited": "https://www.fireproofgames.com/vendors/vacancies",
    "Firmex International Limited": "https://www.firmex.com/company/careers/",
    "First British Clinic Limited": "https://uk.indeed.com/cmp/First-British-Clinic",
    "First Glass London Limited": "https://uk.indeed.com/First-Glass-UK-Ltd-jobs",
    "First Quantum Minerals (UK) Limited": "https://www.first-quantum.com/English/careers/default.aspx",
    "First Years Childcare Limited t/a Banana Moon": "https://www.bananamoonfranchise.com/banana-moon-our-culture/careers-with-banana-moon/",
    "Fiver London Limited": "https://www.fiverr.com/jobs",
    "Flawless Holdings Limited": "https://www.flawlessai.com/careers",
    "Fletcher Day": "https://uk.indeed.com/q-fletcher-day-jobs.html",
    "Flower Corner Limited": "https://www.indeed.com/q-the-flower-corner-jobs.html",
    "Fluent2 Limited": "https://fluent2.co.uk/",
    "Fluro Platform Limited": "https://fluroltd.com/careers/",
    "Fonix Mobile PLC": "https://www.fonix.com/careers/",
    "Fontaine Limited": "https://fontainemodification.com/about-us/careers/",
    "Force Maintenance Team Limited": "https://uk.indeed.com/q-force-maintenance-team-ltd-l-london-jobs.html",
    "Fordgate Management Limited": "https://uk.indeed.com/cmp/Fordgate-Management-Ltd/locations/ENG/London",
    "Foreks Financial Technologies Ltd": "https://www.forex.com/en-uk/about-us/careers/",
    "Forest Cafe & Bistro LTD": "https://uk.indeed.com/m/jobs?q=Forest+Cafe",
    "coleraine church of christ": "https://www.trusselltrust.org/get-help/find-a-foodbank/",
    "comsec consulting uk ltd.": "https://comsecglobal.com/comsec-consulting-is-recruiting-and-were-looking-for-you/",
    "eToro (UK) Limited": "https://www.etoro.com/about/careers/",
    "essDOCS EMEA Limited": "https://www.essdocs.com/company/careers"
}


if __name__ == "__main__":
    d = collections.defaultdict(lambda: 0)
    for _, url in FORBIDDEN_RESPONSE_PAGES.items():
        d[url] = d[url] + 1
    for url, count in sorted([(url, count) for url, count in d.items()], key=lambda t: t[1]):
        if count > 1:
            print(f"{url}: {count}")
